In [1]:
import Levenshtein

In [2]:
def find_most_similar_string_Levenshtein(target, string_list):
    min_distance = float('inf')
    most_similar_string = None
    
    for string in string_list:
        distance = Levenshtein.distance(target, string)
        
        if distance < min_distance:
            min_distance = distance
            most_similar_string = string
            
    return most_similar_string, min_distance

# 示例字符串列表
string_list = ["apple", "banana", "cherry", "dog", "elephant"]

target_string = "aple"  # 要查找相似字符串的目标字符串
most_similar, distance = find_most_similar_string_Levenshtein(target_string, string_list)

print(f"目标字符串: {target_string}")
print(f"最相似字符串: {most_similar}")
print(f"Levenshtein距离: {distance}")

目标字符串: aple
最相似字符串: apple
Levenshtein距离: 1

In [3]:
def jaccard_similarity(set1, set2):
    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))
    return intersection / union if union != 0 else 0.0

def find_most_similar_string_Jaccard(target, string_list):
    max_similarity = 0.0
    most_similar_string = None

    target_set = set(target)

    for string in string_list:
        if isinstance(string, str):  # Filter out non-string values
            string_set = set(string)
            similarity = len(target_set.intersection(string_set)) / len(target_set.union(string_set))
        
            if similarity > max_similarity:
                max_similarity = similarity
                most_similar_string = string
    
    return most_similar_string

In [7]:
import pandas as pd

In [8]:
data = pd.read_excel('HP data.xlsx')

In [9]:
df = pd.read_excel('Tractor ANZ_exercises.xlsx')

In [10]:
make_list = data['Make'].tolist()
model_list = data['Model'].tolist()
MakeDescr_list = df['MakeDescr'].tolist()
ModelDescr_list = df['ModelDescr'].tolist()

In [11]:
new_MakeDescr_list = []
new_ModelDescr_list = []

In [12]:
string_list = make_list
for i in range(len(MakeDescr_list)):
    if isinstance(MakeDescr_list[i], str):
        target_string = MakeDescr_list[i]
        most_similar = find_most_similar_string_Jaccard(target_string, string_list)
        new_MakeDescr_list.append(most_similar)
    else:
        new_MakeDescr_list.append(None)  # Handle non-string values

print(new_MakeDescr_list)

['Deutz Fahr', 'Claas', 'McCormick', 'Deutz Fahr', 'Case', 'John Deere', 'Case', 'Case', 'Valtra', 'Claas', 'Hitachi', 'Case', 'Deutz Fahr', 'Hitachi', 'Case', 'New Holland', 'Kubota', 'Valtra', 'Case', 'New Holland', 'Deutz Fahr', 'Deutz Fahr', 'New Holland', 'Massey Ferguson', 'Massey Ferguson', 'Massey Ferguson', 'Case', 'John Deere', 'Kubota', 'Antonio Carraro', 'Valtra', 'John Deere', 'John Deere', 'John Deere', 'John Deere', 'Valtra', 'John Deere', 'Case', 'John Deere', 'Claas', 'John Deere', 'Iseki', 'Fendt', 'Massey Ferguson', 'New Holland', 'John Deere', 'John Deere', 'New Holland', 'New Holland', 'New Holland', 'New Holland', 'New Holland', 'New Holland', 'New Holland', 'New Holland', 'New Holland', 'New Holland', 'Case', 'JCB', 'Fendt', 'Kubota', 'Kubota', 'John Deere', 'Claas', 'Case', 'John Deere', 'Case', 'Case', 'Valtra', 'Case', 'Case', 'Case', 'John Deere', 'John Deere', 'JCB', 'New Holland', 'Case', 'TYM', 'Valtra', 'Case', 'John Deere', 'Case', 'John Deere', 'Mahindra', 'Farmtrac', 'McCormick', 'Case', 'Antonio Carraro', 'John Deere', 'Zetor', 'Valtra', 'McCormick', 'Claas', 'New Holland', 'Agrale', 'Carraro', 'Case', 'Case', 'John Deere', 'Mahindra', 'Apollo', 'McCormick', 'Case', 'Agrale', 'Kubota', 'New Holland', 'Case', 'Apollo', 'New Holland', 'Farmtrac', 'New Holland', 'Apollo', 'Apollo', 'Massey Ferguson', 'Solis', 'Apollo', 'Apollo', 'Apollo', 'John Deere', 'Lamborghini', 'John Deere', 'Farmtrac', 'Apollo', 'John Deere', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Fendt', 'Fendt', 'Fendt', 'Fendt', 'Fendt', 'Fendt', 'Fendt', 'Fendt', 'Kubota', 'Apollo', 'Apollo', 'Apollo', 'Kubota', 'New Holland', 'New Holland', 'McCormick', 'Apollo', 'Apollo', 'Farmtrac', 'Farmtrac', 'Case', 'Solis', 'Apollo', 'Massey Ferguson', 'Massey Ferguson', 'Apollo', 'Apollo', 'Claas', 'John Deere', 'Fendt', 'New Holland', 'Apollo', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Kubota', 'Deutz Fahr', 'Deutz Fahr', 'Apollo', 'Apollo', 'Apollo', 'Case', 'Farmtrac', 'New Holland', 'Farmtrac', 'Apollo', 'Kubota', 'Kubota', 'Fendt', 'Fendt', 'Fendt', 'Fendt', 'Apollo', 'Massey Ferguson', 'John Deere', 'John Deere', 'McCormick', 'John Deere', 'McCormick', 'Deutz Fahr', 'New Holland', 'Apollo', 'Fendt', 'McCormick', 'Fendt', 'John Deere', 'John Deere', 'Apollo', 'Apollo', 'Apollo', 'Apollo', 'Apollo', 'Apollo', 'Apollo', 'John Deere', 'Case', 'Apollo', 'John Deere', 'John Deere', 'Apollo', 'Valtra', 'Case', 'Apollo', 'Apollo', 'Landini', 'Apollo', 'Apollo', 'Antonio Carraro', 'Apollo', 'McCormick', 'Apollo', 'Apollo', 'Case', 'Claas', 'Apollo', 'Apollo', 'Case', 'John Deere', 'John Deere', 'Kubota', 'Apollo', 'Apollo', 'Case', 'Apollo', 'New Holland', 'Apollo', 'New Holland', 'John Deere', 'Apollo', 'Apollo', 'Landini', 'Apollo', 'Landini', 'Apollo', 'Landini', 'Apollo', 'Apollo', 'Apollo', 'Claas', 'Apollo', 'John Deere', 'Apollo', 'John Deere', 'John Deere', 'John Deere', 'Case', 'New Holland', 'John Deere', 'John Deere', 'John Deere', 'JCB', 'JCB', 'JCB', 'JCB', 'JCB', 'JCB', 'John Deere', 'Apollo', 'Apollo', 'Apollo', 'Apollo', 'McCormick', 'Apollo', 'Apollo', 'Apollo', 'Apollo', 'Kubota', 'Carraro', 'Carraro', 'Claas', 'Claas', 'Apollo', 'John Deere', 'Kubota', 'Apollo', 'Apollo', 'Apollo', 'Landini', 'Valtra', 'Landini', 'Apollo', 'Apollo', 'Apollo', 'Apollo', 'John Deere', 'Landini', 'Landini', 'Apollo', 'Apollo', 'Apollo', 'John Deere', 'Landini', 'New Holland', 'Mahindra', 'Mahindra', 'Case', 'Apollo', 'Apollo', 'John Deere', 'New Holland', 'Mahindra', 'Case', 'Apollo', 'John Deere', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Kubota', 'Case', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Landini', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Mahindra', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Deutz Fahr', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Mahindra', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'John Deere', 'John Deere', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Farmtrac', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Deutz Fahr', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Deutz Fahr', 'Claas', 'Claas', 'Fendt', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Farmtrac', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Massey Ferguson', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Farmtrac', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Case', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Massey Ferguson', 'Claas', 'John Deere', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Landini', 'JCB', 'Case', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'John Deere', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'Antonio Carraro', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Fendt', 'JCB', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'McCormick', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Massey Ferguson', 'Claas', 'John Deere', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Massey Ferguson', 'Claas', 'Case', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Massey Ferguson', 'JCB', 'JCB', 'New Holland', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Deutz Fahr', 'Claas', 'John Deere', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Massey Ferguson', 'Claas', 'Claas', 'Claas', 'Claas', 'Kubota', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'Claas', 'Claas', None, 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Renault', 'Kubota', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Deutz Fahr', 'Claas', 'Claas', 'John Deere', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'John Deere', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Massey Ferguson', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'New Holland', 'Case', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Deutz Fahr', 'Claas', 'Claas', 'Claas', 'McCormick', 'Claas', 'Claas', 'Deutz Fahr', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'JCB', 'Claas', 'John Deere', 'Claas', 'Claas', 'Claas', 'Deutz Fahr', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Claas', 'Deutz Fahr', 'JCB', 'Claas', 'Claas', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Agrale', 'New Holland', 'Case', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'New Holland', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Versatile', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Claas', 'Agrale', 'Deutz Fahr', 'Massey Ferguson', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Claas', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Fendt', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'New Holland', 'Massey Ferguson', 'Deutz Fahr', 'New Holland', 'New Holland', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Zetor', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'McCormick', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'John Deere', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Massey Ferguson', 'Deutz Fahr', None, 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', None, 'Versatile', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'New Holland', 'Deutz Fahr', 'Massey Ferguson', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', None, 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Antonio Carraro', 'Case', 'Case', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Versatile', 'Deutz Fahr', 'John Deere', 'Case', 'Landini', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Zetor', 'Case', 'Kioti', 'Case', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'New Holland', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kubota', 'Deutz Fahr', 'Kioti', 'Case', 'Deutz Fahr', 'Case', 'Antonio Carraro', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Agrale', 'Deutz Fahr', 'John Deere', 'Kioti', 'Deutz Fahr', 'McCormick', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'McCormick', 'New Holland', 'Kioti', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'John Deere', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'McCormick', 'McCormick', 'Claas', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Landini', 'Antonio Carraro', 'Deutz Fahr', 'Massey Ferguson', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Massey Ferguson', 'Deutz Fahr', 'New Holland', 'New Holland', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Case', 'Versatile', 'Kioti', 'Deutz Fahr', 'Kioti', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Solis', 'Kioti', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Antonio Carraro', 'Kioti', 'McCormick', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'New Holland', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'New Holland', 'Landini', 'Massey Ferguson', 'Kioti', 'McCormick', 'Kioti', 'Deutz Fahr', 'Daedong ', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Landini', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Kioti', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'New Holland', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Daedong ', 'John Deere', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'John Deere', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Claas', 'Deutz Fahr', 'John Deere', 'Deutz Fahr', 'Kioti', 'John Deere', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'New Holland', 'Kioti', 'New Holland', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'New Holland', 'Kioti', 'Kioti', 'Kioti', 'Massey Ferguson', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kubota', 'Kioti', 'Case', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Kioti', 'Kioti', 'Case', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'John Deere', 'Deutz Fahr', 'McCormick', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Massey Ferguson', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Antonio Carraro', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Kioti', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Kubota', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Massey Ferguson', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Case', 'Deutz Fahr', 'Deutz Fahr', 'Kioti', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Deutz Fahr', 'Carraro', 'Deutz Fahr', 'De

In [13]:
len(new_MakeDescr_list)

4871

In [14]:
string_list = model_list

for i in range(len(ModelDescr_list)):
    if isinstance(ModelDescr_list[i], str):
        target_string = ModelDescr_list[i]
        most_similar = find_most_similar_string_Jaccard(target_string, string_list)
        new_ModelDescr_list.append(most_similar)
    else:
        new_ModelDescr_list.append(None)  # Handle non-string values

print(new_ModelDescr_list)

['7250 TTV', 'N 180a', 'MTX110', '6160 TTV', '1255 XL', 'L4760', 'Nexos 220', 'Puma 165', 'T191', 'EOS 5.50AR', 'TR633', 'DX 140', 'Agroplus 410', 'TR633', 'STX375', '825', 'M4700', 'YM4500', 'JX75', 'T7.235', 'Farmer 304LS', 'Agroplus F430', '9400T', 'D 4507', '575.4', '4.56', '8345RT', '8R 280', 'M7950HC', 'SRH 9800', '460', 'T9520', '3046R', '1026R', '2038R', 'M120', '6125R', '3039R', '3045R', 'EOS 5.50AR', 'AT33', '4050', 'A82', '6125D', '8300T', '8345R', '7210R', 'T8.320', 'T8.320', 'T8.320', 'T8.320', 'T8.435', 'T8.320', 'T8.320', 'T8.320', 'T8.435', 'T8.320', 'Maxxum 125', 'ST22A', '3039R', 'M4030SU', 'M4030SU', '6140M', '4.56', '1255 XL', '5038D', 'MX240', '8R 310', 'T6040 Elite', 'Magnum 260', 'AF660', 'STX450', '9570R', '9360R', 'TTR 3800', 'T8.360', 'MXU115', 'T7000', 'N101', 'MXM120', '6140R', 'Maxxum 110', '9370R', 'Fastrac 4160', 'TN90F', 'CX85', 'MX90C', 'AT33', 'AF120', 'L245', '4050', 'CX100', 'ORION 7.75', 'T8.390', 'MB85', 'AT33', 'AF660', 'AF660', '9460R', '420.5', '954', 'TL95E', 'MXU125', 'T654', 'L3800', 'TC24DA', None, '354', 'T7.210', '6190R', 'TL100A', 'CS 48', 'Farmall 45C', '6310SE', 'L345', '5042C', '45C', 'EF453', '6190R', '935', 'L235', 'TL2901', '45C', '3038R', 'M108 DC', 'M108 DC', 'M108 DC', 'M108 DC', 'M108 DC', '211P', '211P', '211P', '211P', '211P', '211P', '211P', '211P', 'M108', '45C', '45C', 'EOS 5.50AR', 'Landforce 125', 'T5070', 'TS100A', 'MTX135', '454', '354', 'TL2901', 'TF330', 'Farmall 100N', 'AT33', '454', '354', '40-72', '454', '854', '6-120C', 'Forterra 120', '305 LS', 'T7.185', '954', 'M108 DC', 'M100GX', 'M135GX', 'M108 DC', 'M100GX', 'M100GX', 'M108 DC', 'M100GX', 'M135', 'M135', 'Agroplus 315', 'Agroplus 315', '954', '45C', '75-14 RS', 'B5000', '690T', 'T7.185', '690T', '354', 'M108 DC', 'M108 DC', '211P', '211P', '211P', '211P', '45C', '454', '6195R', '575', 'MTX135', '8310R', 'MC90', 'Landforce 115', 'T4.55', '45C', '6.17', 'CX85', '936', '5090 D', '6145R', '45C', '5042C', '354', '354', '45C', '45R', '45R', '3046R', 'EOS 6.50RS', '45R', '6125M', '6135', 'TC45A', 'N124', 'JX70', '45R', '354', 'T6080 Elite', '45C', '45C', 'TRX 7800S', '45C', 'M9000', '354', 'TC45A', 'TRG 10400', '8R 340', '354', '454', 'EOS 6.50RS', '8360RT', '8360R', 'TM17', 'TC45A', '45R', 'Maxxum 120', 'Landforce 115', 'T5.95', '45C', 'T7040', 'M4062', '354', '354', 'EOS 5.50AR', '45C', 'ORION 7.75', '954', '6180', '45R', '45R', '45R', 'SRX 8400', '354', '8245R', '354', '7210R', '6125R', '40-72', 'Magnum 340', 'TS100A', '8310R', 'AT33', '6115M', '3330', '3330', '3330', '3330', '3330', '3330', '6125M', '75-14 RS', '5042C', '45R', '45R', 'DX 4.50', '45C', '45R', '75-14 RS', '354', 'M7950HC', 'TR55', 'Mach 2', '50A', '50A', '354', '380', 'M7950HC', '75-14 RS', '45C', 'TC45A', '575', 'N134', '6180', '45R', 'RT120', '45C', '45R', '9370R', '575', 'DT160', '45C', '415 DI', '45C', '6130R', 'T9510', 'T7.170', 'C60', '6530', 'CVX 120', '45C', '45R', 'T3030', 'FT 30', 'DK65', 'Proxima Plus 105', '45C', '8310R', 'ERA 3.90', 'Evolution 6865', 'TD4410', 'TRX 7800S', 'Technofarm 85', '8865 super', '7856', 'ST45', '265 DI', '8865', 'F120', 'RX6010', '8865', 'SRX 8400', '8865', '68-12 RS', '4-105', 'Rex 120', '75-12 LS', 'XA 606', 'TRG 9800', '4-105', '7856', 'SRX 9800', '7856', 'Powerfarm 100', '856 XL', 'H-5116', 'Powerfarm 75', 'Steiger 580 Quadtrac', 'ORION 7.75', 'Intrac 2006', 'Arion 410', 'ORION 7.95', 'TX 7800S', '2026R', '260', 'Axion 950', 'Arion 620', 'Arion 620', 'CS 130', 'EOS 5.50AR', 'Arion 630', 'Arion 620', '6215 RC', 'VANTH 5.30', 'Arion 620', '340', 'Arion 530', 'Arion 530', 'VANTH 6.40', 'Arion 620', 'Arion 630', 'Arion 410', 'Arion 630', 'Arion 460', 'Axos 320', 'Arion 610', 'Arion 510', '6-120C', 'Arion 620', 'Arion 620', '106-54 TL', 'DX 3.90', '3630A', 'Arion 430', 'Arion 410', 'EOS 5.50AR', 'ERA 3.90', 'KL26R-PC', 'R 4000', 'Arion 620', 'Arion 450', 'Arion 440', 'EOS 5.50AR', 'Arion 620', 'Axion 840', 'Arion 430', 'Arion 620', 'SRX 8400', 'Axos 340', 'RT140A', 'VANTH 6.40', 'Arion 460', 'NTX380', 'Arion 620', '6-120C', 'Axion 870', 'Tigrone Jona 6400F', 'Arion 620', 'Arion 620', 'Arion 530', '2026R', '90-32 MX', 'AC-10', 'H-658 XA', 'ORION 7.95', 'ORION 7.75', 'Arion 410', 'Arion 460', 'KL26R-PC', 'SX 9400S', 'EOS 5.50AR', 'ERA 3.90', 'VANTH 5.30', 'Arion 660', 'ORION 7.75', 'NTX380', 'Arion 420', 'TX 7800S', 'Arion 650', 'Arion 460', 'SRX 10400', '20-40', 'Arion 630', 'ORION 8.85', 'Arion 650', 'VANTH 6.40', 'Arion 530', 'GC2600', '6215 RC', '6215 RC', '6-120C', 'Arion 620', 'Arion 620', 'Arion 520', '6-120C', 'Axion 800', '6215 RC', '6140 CVT', '8770A', '6215 RC', 'Arion 620', 'Axos 340', '1042 Vario', '6215 RC', 'Arion 430', 'DX 3.90', 'Axion 800', '4050', 'Axion 950', 'CS 130', 'Arion 620', 'Arion 430', '6105R', 'Cergos 340', 'Arion 610', 'EOS 5.50AR', 'Intrac 6.05', 'CS 63', '6215 RC', '6215 RC', '80-12 TX', 'ERA 9.40', 'Axion 830', 'Arion 530', 'Arion 610', '8R 340', 'Agrotron 90', 'EOS 5.50AR', 'Arion 520', '6215 RC', '6215 RC', 'CS 130', 'GC2600', '90-32 MX', 'Arion 460', 'Axion 870', 'Axion 810', 'ORION 7.85', 'ORION 7.85', 'M108 DC', 'Arion 650', '61-12 RS', '5036C', 'ORION 7.75', 'Arion 430', 'Arion 620', 'Farmer 308LS', '6215 RC', 'Arion 430', 'Arion 620', 'Arion 630', 'Arion 430', '6215 RC', 'ORION 8.85', 'Arion 650', 'EOS 5.50AR', 'STX330', 'Arion 460', 'GC2600', 'NTX380', 'Arion 630', 'CS 130', '340', '6140M', 'M650', 'Arion 620', 'EOS 5.50AR', 'Arion 620', 'Axos 340', '6215 RC', '2026R', 'NTX380', 'L3410', 'L3410', '6215 RC', 'EOS 5.50AR', 'VANTH 6.40', '6-120C', 'R 4000', 'EOS 5.50AR', 'Arion 630', 'GC2600', 'Arion 430', '6215 RC', '6215 RC', '6215 RC', '90-32 MX', 'EOS 5.50AR', '8R 340', 'VANTH 6.40', 'ORION 7.75', 'T7.235', 'CS 120', 'VANTH 6.30', '5036C', 'SX 9400S', 'Arion 610', 'Axion 930', 'NTX380', 'EOS 5.50AR', 'NTX380', 'ORION 7.75', 'Arion 620', '6215 RC', 'Arion 460', 'Arion 460', 'Arion 620', 'DT 7000', 'Arion 410', '6215 RC', 'ORION 7.75', '6215 RC', 'Axos 330', 'Arion 420', 'TS100A', '430C', 'Favorit 610SL', 'SRX 8400', 'KL26R-PC', 'Arion 430', 'Axion 850', 'EOS 5.50AR', 'Arion 430', 'Arion 620', 'AT260', 'AF330', 'Intrac 2003', '8R 340', 'KL26R-PC', '6-120C', 'Arion 530', 'EOS 5.50AR', 'DX 3.90', 'KL26R-PC', 'Arion 620', 'EOS 5.50AR', 'ORION 8.85', 'GC2600', 'Arion 430', 'GC2600', 'Arion 620', 'Arion 620', 'M108 DC', 'DX 3.90', 'Arion 620', 'Arion 610', 'AT240', 'NTX380', 'EOS 5.50AR', 'GC2600', '6-120C', 'Arion 460', 'KL26R-PC', 'Arion 430', '90-32 MX', 'VANTH 6.40', 'STX380', 'Arion 630', 'Arion 420', 'EOS 6.50RS', '8770A', 'M125A', 'Arion 430', 'Arion 460', 'Arion 430', 'CS 130', 'Tigrone Jona 6400', 'Arion 410', 'Arion 460', 'Axos 330', 'KL26R-PC', 'Arion 620', 'TD95D', 'DX 3.90', 'Arion 430', '6-120C', 'AT280', 'MXU135', 'ORION 7.95', 'MX90C', 'Arion 440', 'DX 3.90', '6-120C', 'CS 120', 'Arion 620', 'CS 120', 'Arion 620', '5105', 'Arion 410', 'Steiger 400 Rowtrac', 'M7172', 'Axos 320', 'NTX380', 'Axos 320', 'Axos 320', '6140 CVT', '6160 CVT', '6-120C', '90-32 MX', 'Axos 330', 'Arion 410', 'Arion 620', '6215 RC', 'SX 9400S', '6-120C', '8R 250', 'SX 7800S', '260', 'Arion 620', 'ORION 7.95', 'Arion 610', '6-120C', 'Arion 460', 'Arion 460', 'Arion 460', 'Arion 460', 'Arion 460', 'Arion 460', '8R 340', 'Arion 650', '6-120C', 'Arion 460', '6215 RC', '6-120C', '6-120C', 'SX 7800S', 'Maxxum 110', '6110R', 'Arion 410', 'SRX 10400', 'Arion 460', 'Arion 620', '90-32 MX', '354', 'SX 7800S', 'Farmall 95C', 'Arion 460', 'Arion 410', '6-120C', 'RT140A', 'M130', '6-120C', 'NTX300', 'CS 130', 'Arion 610', 'Arion 650', 'Arion 430', 'Arion 430', 'Arion 430', 'Axos 330', '6-120C', 'GC2600', 'RT140A', 'GC2600', 'Arion 610', 'Arion 410', 'Arion 620', '6-120C', 'Arion 460', '30A', 'R 4000', 'AT5390', 'Arion 430', 'VANTH 6.40', 'Arion 620', 'M135A', 'Arion 430', 'Axos 340', 'STA-30', 'Arion 620', 'Arion 440', 'Arion 430', 'Arion 610', 'Arion 410', 'RT140A', '6-120C', 'GC2600', 'Arion 430', 'Arion 460', '6-120C', 'Arion 620', 'Arion 610', 'Steiger 420 Rowtrac', 'Arion 430', 'Prince 325', '4066R', '430C', 'Arion 620', '430C', '6-120C', '6-120C', 'MX5800', 'Arion 460', '2026R', 'AT340', 'Tigrone Jona 6400F', 'Arion 620', 'GC2600', '6-120C', 'AT340', '6-120C', 'Arion 430', '4066R', 'Arion 620', 'Arion 620', 'Arion 620', 'Arion 410', 'Axion 950', 'Axos 340', 'Arion 620', 'Cergos 340', 'Arion 410', '260', 'Arion 620', 'CS 110', 'Arion 430', 'Arion 430', 'Arion 410', 'Arion 430', 'Arion 430', 'Arion 620', 'Arion 650', 'RT100A', '4100 Multi', 'Nexos 240 F', 'Nexos 240 F', 'M100A', 'H-2000 SX', 'H-2000 SX', 'H-2000 SX', 'H-2000 SX', 'H-2000 SX', 'H-2000 SX', 'Nexos 240 F', 'Nexos 240 F', 'Nexos 240 VL', 'Nexos 230', 'Nexos 230', 'Nexos 230', 'Nexos 230', 'Nexos 230', 'Nexos 230', 'Nexos 230', '550DTC', 'GC2600', 'Arion 630', 'Arion 650', 'Axion 850', 'Arion 620', 'Arion 630', 'Agrotron 150.7', 'Axion 830', 'CS2610', 'AF220', 'Fastrac 4220', 'Arion 650', 'Axion 830', 'CS 63', 'Arion 620', 'Axos 340', 'Arion 610', 'RX8030', 'EOS 5.50AR', 'EOS 5.50AR', 'Arion 650', 'Arion 410', 'Arion 440', 'GC2600', 'Arion 440', 'NTX380', '106-54 TL', 'Arion 460', 'Arion 620', 'Arion 630', 'ORION 7.75', '6215 RC', 'Arion 660', 'Arion 460', 'Fastrac 4220', 'Arion 620', 'Arion 520', 'Arion 660', 'Farmer 3S', 'Arion 610', 'Axion 830', 'Arion 650', '30A', 'Fastrac 4220', 'Arion 610', 'L2600', 'Arion 620', 'Nexos 240 VL', 'Axion 830', 'Arion 650', 'Intrac 6.30', 'EOS 5.50AR', 'Arion 430', 'Arion 620', '260', 'Arion 630', 'Arion 430', 'Arion 610', 'Arion 410', 'Agroplus F 310 ecoline', 'VANTH 6.40', 'Tigrone Jona 6400F', 'Maxxum 125', 'Arion 620', 'Favorit 620LS', 'Arion 530', '6110R', 'Arion 450', 'AF220', 'Arion 610', '976', 'Nexos 230', '2360', 'Agroplus 410 ecoline', 'Arion 430', 'Arion 620', 'Arion 610', 'Arion 650', 'Nexos 240 VL', 'Arion 620', 'Arion 660', 'T7030', 'Arion 620', 'Arion 630', 'Arion 610', 'Arion 450', 'Axion 830', '6120.4 TTV', '6.05', 'Arion 620', 'RT120A', 'Steiger 380', 'Farmer 311', 'CVX 150', 'EOS 5.50AR', 'Axion 920', 'Axion 870', 'Fastrac 4220', 'Arion 460', 'Arion 650', 'ORION 8.85', 'Arion 620', 'Arion 610', 'Arion 620', 'GC2600', 'Arion 460', 'Arion 620', 'Arion 620', 'Favorit 620LS', 'Tigrone Jona 6400F', '6215 RC', 'EOS 5.50AR', 'Arion 510', 'Axos 340', 'Puma 165', 'Arion 460', 'Tigrone Jona 6400F', 'Arion 620', 'Arion 620', 'EOS 5.50AR', 'Arion 630', 'Arion 630', 'Arion 620', 'Arion 650', 'Arion 630', 'Arion 430', 'Agroplus 410 ecoline', 'Temis 630', 'Intrac 2006', 'Arion 620', '2026R', 'Ares 697', '6205', 'Arion 620', 'Favorit 610SL', 'Arion 460', 'Arion 460', 'Axion 810', '2240', 'Arion 630', 'Axion 820', 'Arion 440', 'Arion 530', 'Xerion 3300', 'Arion 650', '6105R', 'Arion 610', 'Arion 430', 'Agrokid 220', 'Arion 620', 'Arion 410', '6215 RC', '2240', 'Arion 620', 'Arion 620', 'Arion 530', '5115ML', 'Arion 430', 'Arion 630', 'AF330', 'Arion 440', '260', '260', 'Arion 410', 'Arion 460', 'Atlas 100', 'Arion 620', '3500C', 'GC2600', 'Arion 620', 'SRX 10400', '8R 340', '6215 RC', 'Arion 620', 'T7.250', 'EOS 5.50AR', 'Arion 650', 'VANTH 6.40', 'VANTH 6.40', 'Arion 620', 'Fastrac 4220', '6215 RC', 'GC2600', 'ORION 7.75', '6215 RC', 'SRX 10400', '6110R', 'EOS 5.50AR', 'MXU100', 'N 180a', 'VANTH 6.40', 'Talos 130', 'Axion 850', 'Arion 460', '6215 RC', 'EOS 5.50AR', 'CS 130', 'Arion 510', 'ORION 7.75', 'EOS 5.50AR', 'EOS 5.50AR', 'Arion 650', 'Arion 460', '6215 RC', 'Arion 610', '7290R', '2240', 'Fastrac 4220', 'Arion 530', 'Arion 620', 'ORION 8.85', 'Arion 460', 'Arion 620', 'Arion 460', 'NTX380', 'Arion 620', 'Arion 450', 'MTX120', 'Arion 430', 'Arion 430', '2240', 'Arion 410', '305 LS', '4065E', 'Arion 460', 'M4062', 'L2600', 'Arion 460', 'Arion 620', 'Arion 630', 'Arion 630', 'STX330', 'RT140A', 'Arion 660', '4050', 'CS 120', 'Optum 270', 'R 4000', 'Landforce 125', 'TL80', 'CX80', 'Arion 460', '454', 'Fastrac 1115', '2032R', 'Agroplus F 310 ecoline', 'Maxxum 115', '6215 RC', 'Arion 620', 'Axos 320', 'Arion 620', 'Arion 660', 'Arion 620', '430C', 'Favorit 610SL', 'Arion 620', 'Arion 630', '5076EF', 'FT 26', '160', 'Farmall 120C', 'GC2600', 'Arion 620', 'K420', 'Arion 420', 'M4062', 'Nexos 240 VL', 'Nexos 240 VL', 'Nexos 240 VL', 'Fastrac 4220', 'Arion 610', 'Nexos 240 VL', 'GC2600', 'Axos 340', 'TN95F', '575', '340', 'Arion 460', 'Arion 620', 'Arion 450', 'Axos 340', 'Arion 620', 'Arion 630', 'ERA 3.90', 'Arion 630', 'Axion 820', 'Arion 450', 'T603', 'Arion 430', 'Arion 630', 'Axos 340', 'Arion 430', 'Arion 610', 'Arion 430', 'PowerStar 120', 'Arion 620', '7260R', 'Nexos 230', 'Arion 430', 'Arion 620', 'VANTH 6.40', 'M8540', 'Arion 460', 'Forterra 120 HSX', 'Arion 420', 'Arion 620', 'Arion 430', '2240', 'Steiger 620 Quadtrac', '4044R', 'Arion 660', 'EOS 5.50AR', 'T603', 'Arion 620', 'Arion 410', 'Arion 620', 'Arion 510', 'R65', '5105', 'Arion 420', 'Arion 620', 'Axos 330', 'Arion 610', 'Arion 430', 'Arion 440', 'Arion 520', 'Arion 620', 'Talos 220', 'Arion 430', 'Arion 420', '5105', 'EOS 5.50AR', 'SX 9400S', '6140', 'Arion 620', 'Arion 620', '340', 'Axion 850', 'Arion 420', 'Arion 620', 'Arion 620', 'Arion 620', 'Arion 410', 'Arion 410', 'Temis 630', 'Arion 610', 'Arion 430', 'Arion 620', 'Arion 630', 'Arion 460', 'Arion 620', 'T5.100', '6215 RC', 'Arion 430', 'Ares 556', 'Arion 430', 'Arion 620', 'Arion 620', 'C80 Max', 'Axion 850', 'Arion 410', 'Nexos 240 VL', 'Nexos 240 VL', 'Arion 610', 'VANTH 5.30', 'Arion 620', 'Arion 650', 'Arion 660', '6215 RC', 'Arion 620', 'Arion 610', 'Nexos 240 VL', '3046R', 'EOS 5.50AR', 'Arion 430', '6215 RC', 'Arion 630', '260', '40-72', '260', 'Arion 650', 'Arion 620', 'CS 110', 'Sc2400', 'Axion 850', 'Arion 620', 'LT90', 'Farmall 85C', 'CS2610', 'Arion 430', 'Arion 620', '260', 'Arion 630', 'Arion 610', '260', 'Arion 620', 'Arion 620', 'ST28A', 'Arion 410', 'Arion 610', 'SRX 10400', 'MC120', 'Arion 410', 'Arion 460', 'Agrotron 120', 'EOS 5.50AR', 'Arion 620', 'Arion 620', 'Arion 620', 'Arion 620', 'Arion 450', 'Arion 630', 'Arion 430', 'Arion 650', 'Arion 430', '2240', 'Arion 410', 'M4062', 'Arion 620', 'Arion 430', 'Arion 620', 'P100', 'Arion 460', 'Arion 620', 'Nexos 240 VL', 'Arion 430', 'Arion 460', 'Arion 430', 'Arion 530', 'Favorit 600SL', 'Arion 620', 'Temis 630', '460', 'Axion 810', 'Arion 520', 'Arion 610', 'Arion 620', 'Arion 430', 'Arion 620', '2240', '2240', 'Ares 697', 'Arion 430', '6165 RC', 'Favorit 816', 'Favorit 610S', '6125 TTV', 'Agrotron 106', 'Proxima Plus 85', 'T7030', 'LT75A', 'SRH 9800', 'Fastrac 1135', '6215 RC', '6205', '6155', 'TS115', '4.51', 'RX7620', 'Fastrac 4160', '1255 XL', '6140.4 TTV', '125', 'Agrotron 110', 'Favorit 615SL', 'G115', 'M620', '6155', '6135', 'PowerStar 120', 'RX8030', '250', '3039R', 'Agrolux 410', '6130', 'Favorit 600SL', 'MX90C', '7R 310', 'Fastrac 1135', 'M620', '6185', '115 GS', 'Agrofarm 100', '6155', '5105', '6160 TTV', '6165 RC', 'Favorit 512C', '6140.4 TTV', '4100.4E', 'CK3710', '5105', 'C100 Max High Clear', 'DK5810', '6215 RC', 'AT260', '6185', 'TU125F', 'DK4810', 'Agrofarm 100', 'C60 Max', 'C60 Max', 'TTV 630', '6165 RC', '6125D', '6125D', 'TTV 620', '6160 TTV', 'M620', 'Axion 850', 'Mistral 55', 'Favorit 512C', 'B72', '6215 RC', '6135', '6165 RC', 'T6050 Elite', 'DS3510', '6185 RC', 'Magnum 315', 'RT165A', '6160 TTV', '6125 TTV', '6155', '6140', 'Favorit 615SL', 'T10520', 'CVX 120', 'Arion 520', '6140', '6205', '9430T', '6205', '6135', 'Favorit 615SL', 'Fastrac 1115', 'Agrofarm 115', '6185 RC', '284S', '6185 RC', 'G135 Max', '6205', 'M650', 'Puma 125', 'T7.245', '756', 'Favorit 615SL', 'T7040', 'LT90', 'Agrotron 115', 'Crystal 150', '6155', 'M600', '1156 Vario MT', 'TTR 10400', 'RT155A', 'Puma 165', '6125 TTV', 'Favorit 615SL', 'Favorit 615SL', '6180', 'TV140', 'RT165A', 'Favorit 615SL', 'TGF 10400', 'TGF 10400', '1156 Vario MT', '1156 Vario MT', '4.07', 'Puma 165', 'Steiger 620', 'KL340', 'CS2610', '5105', '1026R', '4.51', 'RT135', '6125 TTV', 'Landforce 115', 'EOS 5.50AR', '160', 'M600', '6205', '6205', 'Landforce 115', 'Agrofarm 100', 'Puma 145', 'Intrac 2005', 'Workmaster 65', 'Proxima Plus 10541', 'MC135', '6135E', '6135', 'SRX 10400', 'Agrofarm 100', 'M650', 'CS 110', 'Dieselross F15', 'Agrofarm 100', '6165 RC', 'CK3010', 'Steiger 620', '6135', 'Agroplus 410 ecoline', '6140M', 'Agrofarm 115', 'PX1052', 'Favorit 600SL', 'Favorit 615SL', '4.51', 'EOS 5.50AR', '7250 TTV', 'Vestrum 130', 'Steiger 620', '5105', 'T10520', '115', 'K610', '2345F', 'Agrofarm 115', '6155 TTV', 'Agrolux 410', '6165 RC', '6185 RC', '6125 TTV', 'Favorit 615SL', '115', 'Farmall 75N', 'TTV 620', 'Farmall 40A', '720.5', 'T6020 Plus', 'Favorit 600SL', 'PX1052', 'Agrofarm 100', 'T7060', '5103E', '6714S', '4100 Multi', 'Agrolux 65', 'Fastrac 1135', 'Steiger 600', '2032R', 'T603', 'RT120A', '125', 'Steiger 600 Quadtrac', '6185', 'Agrofarm 100', '6185 RC', '5105', 'CK2510', 'T8050', 'TGF 7800S', 'EOS 6.50RS', 'CS2610', 'CK2510', 'T4.105', 'RX8030', 'K610', 'Farmall 40A', '8280 TTV', '6105R', '55-12 LB', 'Atlantis 100', 'Agrofarm 100', 'ST60A', 'PX1052', '125', 'KL340', 'TRG 10400', '4.47', 'SRX 8400', 'PX1052', 'AF660', '7R 310', '5105', '6130', 'AT33', '6125 TTV', 'TTV 630', 'Vestrum 130', 'DT160', '6185', 'DX 3.70', 'M600', 'RT165A', '6115M', 'Steiger 600', '6155', 'Favorit 615SL', 'TN60A', 'Favorit 600SL', 'Agroplus 320', 'Agroplus 320', 'TS100', 'TTR 10400', '160', 'Agrofarm 100', 'T10520', 'Agrofarm 115', '6310SE', 'M620', 'Vestrum 130', 'Maxxum 125', 'Agrotron 165.7', 'M620', 'TL60E', 'Agrolux 65', 'Fastrac 2150', 'T10520', 'K610', 'M135GX', '856 XL', 'CS2610', 'TTR 3800', 'TGF 10400', 'DX 86', 'TRX 9800', 'TTV 630', 'M650', 'M600', '4.51', 'PX1153', '4080.4E', 'Steiger 600 Quadtrac', 'Agroplus F 310 ecoline', 'K610', '6125M', '5105', '6130', 'CVX 150', 'Agrolux 65', 'TGF 10400', '6205', 'C60', 'M600', 'MTX150', 'TS100A', 'Favorit 610SL', '115', 'SRX 8400', '6140.4 TTV', 'CK3010', 'DK5810', '115', 'CS2610', 'RX7620', '6215 RC', '6185', '9340 TTV', 'DK4810', '1455 XL', '260', 'NX6010', 'GC2300', 'PowerStar 65', 'B1402', 'C105 Max', 'MTX120', 'Arion 520', 'Fastrac 2140', '6135', '6155', '950', 'TTR 7800', '6135', '454', '4.51', '6155', 'Agrofarm 100', '6135', 'M600', 'CS2610', '115', 'M620', 'M600', 'CX95', '6165 RC', 'T6020', 'TM150', 'Agroplus F 310 ecoline', '115', '6135', '6205', '4.80', 'G135 Max', 'JXU 95', 'Agrofarm 115', '4.51', 'Vestrum 130', '4.51', '4080E', 'T4.105', 'Favorit 610SL', 'Agrotron 115', '6135', '6190 TTV', '115', 'DK4810', '115', 'Super 90', 'Pales 210', 'Technofarm 70', 'Agrofarm 100', 'CS2610', 'Arion 410', '6115M', 'Agrofarm 100', '6155 TTV', 'Agrofarm 100', 'CS2610', '5 080H', '4.51', 'DK4810', 'Agrofarm 115', 'Agrotron 106', 'Forterra 140 HD', '6205', 'TS2210', 'M600', 'Pales 210', 'DK5810', 'Forterra 120', '115', '115', 'T9000', '310', 'Farmer 105LS', 'Puma 165', 'Steiger 370 Rowtrac', 'Agroplus 410 ecoline', 'T7.200', 'M600', 'CS 120', 'Agrofarm 100', 'Agrofarm 100', 'T4.105', '6165 RC', 'T6010', 'Vision 105', '976', 'CS2610', 'MTX110', 'CS 120', '6130.4 TTV', 'DK90C', '4080E', 'CK3710', 'CS2610', 'Agrofarm 115', 'Agrotron 115', 'Forterra 105', '5105', 'Steiger 350 Rowtrac', 'Fastrac 1135', 'M600', 'CS2610', 'PowerStar 120', 'Agrolux 65', 'Agrofarm 115', 'Agrofarm 115', 'Agrolux 65', 'Agrofarm 420', 'Vision 95', 'Steiger 370 Rowtrac', '4.51', '4080.4E', '115', 'K420', '115', 'PX1052', 'CK3010', 'CK3010', '6135', 'CS 130', '6185 RC', 'Favorit 610SL', 'K610', 'Agrolux 65', '1156 Vario MT', 'TS115', 'Agrofarm 115', 'TTR 3800', 'Steiger 620', 'Proxima Plus 105', 'T10520', '4.51', 'DK80', '2360', 'Agrotron 120 MK3', 'Agrolux 410', 'CS2610', '6185 RC', 'PX1052', '1156 Vario MT', 'Agrofarm 100', 'DX100', 'CK30', 'Elios 230', 'Agrofarm 100', 'Favorit 615SL', 'Farmer 309Ci', 'Workmaster 60', 'CK3010', 'Puma 165', 'Agrotron 106', '575', '5105', '5041C', 'CK2510', 'PX1153', '5090M', 'T4.105', 'Puma 165', '1255 XL', 'Agroplus 320', 'Agrofarm 420', 'M620', 'T4.105', 'TM140', 'Forterra 130 HD', 'T6500', 'Agrolux 410', 'Fastrac 145', 'Agrofarm 100', 'M620', 'T680', 'PX1153', 'RX8030', 'DX100', 'M 9086', 'Fastrac 1135', '6205', 'CS2610', 'CK3010', 'CS2610', '8R 230', 'F420', '2040S', 'Steiger

In [15]:
len(new_ModelDescr_list)

4871

In [16]:
data['CombinedColumn'] = data['Make'].astype(str) + ' ' + data['Model'].astype(str)
column1_list = data['CombinedColumn'].tolist()
column2_list = data['HP'].tolist()
keys = column1_list
values = column2_list
dictionary = dict(zip(keys,values))
print(dictionary)

{'AGCO DT180A': 215, 'AGCO DT200A': 235, 'AGCO DT205B': 240, 'AGCO DT220A': 260, 'AGCO DT225B': 265, 'AGCO DT240A': 290, 'AGCO DT250B': 290, 'AGCO DT275B': 320, 'AGCO RT100A': 128, 'AGCO RT110A': 135, 'AGCO RT120A': 145, 'AGCO RT140A': 170, 'AGCO RT155A': 185, 'AGCO RT165A': 200, 'AGCO RT180A': 215, 'AGCO DT160': 177, 'AGCO DT180': 215, 'AGCO DT200': 235, 'AGCO DT225': 250, 'AGCO LT75A': 100, 'AGCO LT85A': 105, 'AGCO LT90A': 110, 'AGCO LT95A': 115, 'AGCO RT100': 128, 'AGCO RT115': 127, 'AGCO RT120': 150, 'AGCO RT130': 144, 'AGCO RT135': 150, 'AGCO RT140': 170, 'AGCO RT145': 161, 'AGCO RT150': 166, 'AGCO ST22A': 22, 'AGCO ST24A': 22, 'AGCO ST28A': 28, 'AGCO ST33A': 33, 'AGCO ST34A': 33, 'AGCO ST41A': 40, 'AGCO ST47A': 47, 'AGCO ST52A': 52, 'AGCO ST60A': 46, 'AGCO 8360': 360, 'AGCO 8425': 425, 'AGCO GT45': 52, 'AGCO GT55': 56, 'AGCO GT65': 71, 'AGCO GT75': 83, 'AGCO LT70': 77, 'AGCO LT75': 100, 'AGCO LT85': 94, 'AGCO LT90': 110, 'AGCO RT95': 105, 'AGCO ST25': 23, 'AGCO ST30': 28, 'AGCO ST32': 33, 'AGCO ST35': 33, 'AGCO ST40': 40, 'AGCO ST45': 44, 'AGCO ST55': 55, 'AGCO Allis 4650': 50, 'AGCO Allis 4660': 57, 'AGCO Allis 5650': 53, 'AGCO Allis 5660': 63, 'AGCO Allis 5670': 69, 'AGCO Allis 5680': 80, 'AGCO Allis 6670': 69, 'AGCO Allis 6680': 79, 'AGCO Allis 6690': 86, 'AGCO Allis 7600': 95, 'AGCO Allis 7630': 122, 'AGCO Allis 7650': 146, 'AGCO Allis 8610': 114, 'AGCO Allis 8630': 132, 'AGCO Allis 8745': 77, 'AGCO Allis 8765': 94, 'AGCO Allis 8775': 105, 'AGCO Allis 8785': 122, 'AGCO Allis 9130': 150, 'AGCO Allis 9150': 166, 'AGCO Allis 9170': 192, 'AGCO Allis 9190': 214, 'AGCO Allis 9435': 150, 'AGCO Allis 9455': 172, 'AGCO Allis 9630': 150, 'AGCO Allis 9635': 150, 'AGCO Allis 9650': 172, 'AGCO Allis 9655': 172, 'AGCO Allis 9670': 194, 'AGCO Allis 9675': 194, 'AGCO Allis 9690': 216, 'AGCO Allis 9695': 216, 'AGCO Allis 9735': 138, 'AGCO Allis 9745': 161, 'AGCO Allis 9755': 177, 'AGCO Allis 9765': 200, 'AGCO Allis 9775': 222, 'AGCO Allis 9785': 250, 'AGCO Allis 9815': 238, 'Agrale 5075.4': 75, 'Agrale 575.4': 75, 'Agrale 5105': 105, 'Agrale 6180': 168, 'Antonio Carraro Tigrone Jona 6400F': 56, 'Antonio Carraro Tigrone Jona 5800': 48, 'Antonio Carraro Tigrone Jona 6400': 56, 'Antonio Carraro Tigrone 5800': 48, 'Antonio Carraro Tigre 4000F': 38, 'Antonio Carraro Tigre 4000': 31, 'Antonio Carraro SRX 10400': 95, 'Antonio Carraro TGF 7800S': 71, 'Antonio Carraro TGF 9400S': 87, 'Antonio Carraro TGF 10400': 95, 'Antonio Carraro TRG 10400': 95, 'Antonio Carraro TRX 7800S': 71, 'Antonio Carraro TRX 10400': 95, 'Antonio Carraro TTR 10400': 95, 'Antonio Carraro SRH 9800': 87, 'Antonio Carraro SRX 8400': 70, 'Antonio Carraro SRX 9800': 87, 'Antonio Carraro SX 7800S': 71, 'Antonio Carraro SX 9400S': 87, 'Antonio Carraro TGF 9800': 87, 'Antonio Carraro TRG 9800': 87, 'Antonio Carraro TRH 9800': 87, 'Antonio Carraro TRX 9800': 87, 'Antonio Carraro TTR 3800': 36, 'Antonio Carraro TTR 4400': 38, 'Antonio Carraro TTR 7800': 71, 'Antonio Carraro TTR 9800': 87, 'Antonio Carraro TX 7800S': 71, 'Antonio Carraro Mach 2': 87, 'Antonio Carraro Mach 4': 87, 'Apollo 1104': 110, 'Apollo 254': 25, 'Apollo 354': 35, 'Apollo 454': 45, 'Apollo 554': 55, 'Apollo 854': 85, 'Apollo 954': 95, 'Carraro 230 Super 10': nan, 'Carraro 420.5': 37, 'Carraro 454DT': nan, 'Carraro 520.5': 49, 'Carraro 645DT': nan, 'Carraro 720.5': 64, 'Carraro 820.5': 74, 'Carraro 920.5': 83, 'Carraro 3500C': 31, 'Carraro 4500C': 45, 'Carraro 5000C': 50, 'Carraro 88.4': nan, 'Carraro 98.2': 96, 'Carraro 98.4': 96, 'Carraro 3000': 26, 'Carraro 3500': 31, 'Carraro 4500': 45, 'Carraro 5000': 50, 'Carraro 6000': 56, 'Carraro 6500': 61, 'Carraro 7000': 69, 'Carraro 7500': 78, 'Carraro 734': nan, 'Case Steiger 450 Quadtrac': 450, 'Case Steiger 470 Quadtrac': 470, 'Case Steiger 500 Quadtrac': 500, 'Case Steiger 540 Quadtrac': 535, 'Case Steiger 550 Quadtrac': 550, 'Case Steiger 580 Quadtrac': 580, 'Case Steiger 600 Quadtrac': 600, 'Case Steiger 620 Quadtrac': 620, 'Case Steiger 350 Rowtrac': 350, 'Case Steiger 370 Rowtrac': 370, 'Case Steiger 400 Rowtrac': 400, 'Case Steiger 420 Rowtrac': 420, 'Case Steiger 450 Rowtrac': 450, 'Case Steiger 470 Rowtrac': 470, 'Case Steiger 500 Rowtrac': 500, 'Case Farmall DX18E': 18, 'Case Farmall DX24E': 24, 'Case Steiger 385QT': 385, 'Case Steiger 435QT': 435, 'Case Steiger 485QT': 485, 'Case Steiger 530QT': 535, 'Case Steiger 535QT': 535, 'Case Farmall 100C': 99, 'Case Farmall 100N': 98, 'Case Farmall 105U': 105, 'Case Farmall 105C': 106, 'Case Farmall 105N': 106, 'Case Farmall 105V': 106, 'Case Farmall 105A': 112, 'Case Farmall 110A': 110, 'Case Farmall 110C': 107, 'Case Farmall 110N': 106, 'Case Farmall 110V': 106, 'Case Farmall 110U': 107, 'Case Farmall 115U': 115, 'Case Farmall 115C': 115, 'Case Farmall 115A': 120, 'Case Farmall 120A': 118, 'Case Farmall 120C': 117, 'Case Farmall 120U': 117, 'Case Farmall 125A': 125, 'Case Farmall 130A': 130, 'Case Farmall 140A': 140, 'Case Farmall DX21': 21, 'Case Farmall DX24': 24, 'Case Farmall DX29': 29, 'Case Farmall DX33': 33, 'Case Farmall DX48': 48, 'Case Farmall DX55': 55, 'Case MXU115 Value': 116, 'Case MXU130 Value': 131, 'Case Farmall 30B': 28, 'Case Farmall 30C': 32, 'Case Farmall 35B': 38, 'Case Farmall 35C': 36, 'Case Farmall 35A': 35, 'Case Farmall 40B': 41, 'Case Farmall 40C': 40, 'Case Farmall 40A': 40, 'Case Farmall 45A': 45, 'Case Farmall 45C': 45, 'Case Farmall 50B': 47, 'Case Farmall 50C': 45, 'Case Farmall 50A': 50, 'Case Farmall 55A': 54, 'Case Farmall 55C': 55, 'Case Farmall 60A': 60, 'Case Farmall 65C': 64, 'Case Farmall 65A': 64, 'Case Farmall 70A': 70, 'Case Farmall 75C': 76, 'Case Farmall 75A': 74, 'Case Farmall 75N': 76, 'Case Farmall 80N': 74, 'Case Farmall 80V': 74, 'Case Farmall 85C': 84, 'Case Farmall 85U': 85, 'Case Farmall 90C': 86, 'Case Farmall 95C': 95, 'Case Farmall 95U': 95, 'Case Farmall 95N': 95, 'Case Farmall 95A': 97, 'Case Steiger 330': 330, 'Case Steiger 335': 335, 'Case Steiger 350': 350, 'Case Steiger 370': 370, 'Case Steiger 380': 380, 'Case Steiger 385': 385, 'Case Steiger 400': 400, 'Case Steiger 420': 420, 'Case Steiger 430': 430, 'Case Steiger 435': 435, 'Case Steiger 450': 450, 'Case Steiger 470': 470, 'Case Steiger 480': 480, 'Case Steiger 485': 485, 'Case Steiger 500': 500, 'Case Steiger 535': 535, 'Case Steiger 540': 535, 'Case Steiger 550': 550, 'Case Steiger 580': 580, 'Case Steiger 600': 600, 'Case Steiger 620': 620, 'Case Vestrum 100': 100, 'Case Vestrum 130': 130, 'Case Farmall 31': 31, 'Case Farmall 35': 35, 'Case Farmall 40': 40, 'Case Farmall 45': 45, 'Case Farmall 50': 50, 'Case Farmall 55': 55, 'Case Farmall 60': 60, 'Case Farmall 70': 65, 'Case Farmall 80': 72, 'Case Farmall 90': 84, 'Case Farmall 95': 90, 'Case Magnum 180': 180, 'Case Magnum 190': 190, 'Case Magnum 200': 200, 'Case Magnum 210': 210, 'Case Magnum 215': 221, 'Case Magnum 220': 220, 'Case Magnum 225': 225, 'Case Magnum 235': 235, 'Case Magnum 240': 240, 'Case Magnum 245': 248, 'Case Magnum 250': 250, 'Case Magnum 260': 257, 'Case Magnum 275': 275, 'Case Magnum 280': 280, 'Case Magnum 290': 284, 'Case Magnum 305': 304, 'Case Magnum 310': 310, 'Case Magnum 315': 312, 'Case Magnum 335': 330, 'Case Magnum 340': 340, 'Case Magnum 370': 367, 'Case Magnum 380': 380, 'Case Maxxum 110': 110, 'Case Maxxum 115': 115, 'Case Maxxum 120': 129, 'Case Maxxum 125': 125, 'Case Maxxum 130': 130, 'Case Maxxum 135': 135, 'Case Maxxum 140': 139, 'Case Maxxum 145': 145, 'Case Maxxum 150': 145, 'Case Puma 140 X': 140, 'Case Puma 150 X': 150, 'Case Puma 165 X': 165, 'Case Optum 270': 271, 'Case Optum 300': 300, 'Case Puma 115': 115, 'Case Puma 125': 125, 'Case Puma 130': 131, 'Case Puma 140': 140, 'Case Puma 145': 146, 'Case Puma 150': 150, 'Case Puma 155': 155, 'Case Puma 160': 160, 'Case Puma 165': 165, 'Case Puma 170': 167, 'Case Puma 180': 180, 'Case Puma 185': 185, 'Case Puma 195': 195, 'Case Puma 200': 200, 'Case Puma 210': 210, 'Case Puma 215': 215, 'Case Puma 220': 220, 'Case Puma 225': 225, 'Case Puma 230': 231, 'Case Puma 240': 240, 'Case STX375QT': 375, 'Case STX380QT': 380, 'Case STX425QT': 425, 'Case STX430QT': 430, 'Case STX440QT': 440, 'Case STX450QT': 450, 'Case STX480QT': 480, 'Case STX500QT': 500, 'Case STX530QT': 535, 'Case 1056 XL': 105, 'Case 1255 XL': 125, 'Case 1455 XL': 145, 'Case CVX 120': 120, 'Case CVX 130': 130, 'Case CVX 150': 150, 'Case CVX 170': 170, 'Case JX1060C': 57, 'Case JX1070C': 70, 'Case JX1070U': 71, 'Case JX1075C': 75, 'Case JX1075N': 75, 'Case JX1080U': 80, 'Case JX1085C': 80, 'Case JX1090U': 90, 'Case JX1095C': 90, 'Case JX1095N': 91, 'Case JX1100U': 98, 'Case JXU 105': 104, 'Case JXU 115': 111, 'Case 743 XL': 67, 'Case 745 XL': 72, 'Case 844 XL': 80, 'Case 856 XL': 85, 'Case 956 XL': 95, 'Case 9370QT': 360, 'Case 9380QT': 400, 'Case CS 110': 103, 'Case CS 120': 113, 'Case CS 130': 123, 'Case CS 150': 143, 'Case JX100U': 92, 'Case JXU 75': 75, 'Case JXU 85': 84, 'Case JXU 95': 95, 'Case MX100C': 100, 'Case MXM120': 122, 'Case MXM130': 129, 'Case MXM140': 142, 'Case MXM155': 153, 'Case MXM175': 174, 'Case MXM190': 190, 'Case MXU100': 100, 'Case MXU110': 115, 'Case MXU115': 116, 'Case MXU125': 125, 'Case MXU135': 135, 'Case STX275': 275, 'Case STX280': 280, 'Case STX325': 325, 'Case STX330': 330, 'Case STX375': 375, 'Case STX380': 380, 'Case STX425': 425, 'Case STX430': 430, 'Case STX440': 440, 'Case STX450': 450, 'Case STX480': 480, 'Case STX500': 500, 'Case STX530': 530, 'Case 10-18': 20, 'Case 12-20': 22, 'Case 15-27': 30, 'Case 18-32': 35, 'Case 20-40': 44, 'Case 22-40': 44, 'Case 25-45': 50, 'Case 30-60': 66, 'Case 40-72': 80, 'Case 210-B': 33, 'Case 211-B': 33, 'Case 300-B': nan, 'Case 301-B': nan, 'Case 302-B': nan, 'Case 310-B': 41, 'Case 311-B': 41, 'Case 312-B': nan, 'Case 410-B': 41, 'Case 411-B': 41, 'Case 510-B': 50, 'Case 511-B': 50, 'Case 610-B': 50, 'Case 611-B': 50, 'Case 614-B': nan, 'Case 700-B': 60, 'Case 800-B': 60, 'Case 801-B': 60, 'Case 802-B': 60, 'Case 803-B': 60, 'Case 810-B': 60, 'Case 811-B': 61, 'Case 812-B': 60, 'Case 813-B': 60, 'Case 900-B': 78, 'Case 910-B': 78, 'Case 2470B': 212, 'Case 485XL': 52, 'Case 585XL': 60, 'Case 685XL': 69, 'Case 785XL': 77, 'Case 885XL': 83, 'Case CS 48': 48, 'Case CS 52': 52, 'Case CS 58': 58, 'Case CS 63': 63, 'Case CS 68': 68, 'Case CS 75': 75, 'Case CS 78': 78, 'Case CS 86': 86, 'Case CS 94': 94, 'Case CX100': 100, 'Case DX22E': 22, 'Case DX25E': 25, 'Case JX80U': 74, 'Case JX90U': 84, 'Case MX80C': 84, 'Case MX90C': 90, 'Case MX100': 100, 'Case MX110': 110, 'Case MX120': 120, 'Case MX135': 135, 'Case MX150': 144, 'Case MX170': 161, 'Case MX180': 161, 'Case MX200': 183, 'Case MX210': 200, 'Case MX215': 221, 'Case MX220': 205, 'Case MX230': 234, 'Case MX240': 227, 'Case MX245': 248, 'Case MX255': 262, 'Case MX270': 261, 'Case MX275': 275, 'Case MX285': 287, 'Case MX305': 304, 'Case 310C': 42, 'Case 310E': 40, 'Case 1010': 100, 'Case 1031': 113, 'Case 1070': 112, 'Case 1090': 122, 'Case 1170': 135, 'Case 1175': 135, 'Case 1190': 47, 'Case 1194': 49, 'Case 1200': 133, 'Case 1210': nan, 'Case 1270': 141, 'Case 1290': 58, 'Case 1294': 62, 'Case 1370': 158, 'Case 1390': 66, 'Case 1394': 77, 'Case 1410': 90, 'Case 1470': 161, 'Case 1490': 83, 'Case 1494': 85, 'Case 1570': 200, 'Case 1594': 97, 'Case 1690': 100, 'Case 1694': 112, 'Case 1896': 105, 'Case 2090': 120, 'Case 2094': 127, 'Case 2096': 128, 'Case 2290': 143, 'Case 2294': 154, 'Case 2390': 178, 'Case 2394': 197, 'Case 2470': 213, 'Case 2590': 200, 'Case 2594': 217, 'Case 2670': 256, 'Case 2870': 300, 'Case 3294': 197, 'Case 4490': 210, 'Case 4494': 213, 'Case 4496': 213, 'Case 4690': 261, 'Case 4694': 261, 'Case 4890': 300, 'Case 4894': 300, 'Case 4994': 400, 'Case 1120': 19, 'Case 1130': 23, 'Case 1140': 27, 'Case 2120': 44, 'Case 2130': 52, 'Case 2140': 61, 'Case 2150': 71, 'Case 3220': 53, 'Case 3230': 60, 'Case 3394': 180, 'Case 3594': 202, 'Case 4210': 72, 'Case 4230': 84, 'Case 4240': 104, 'Case 5120': 94, 'Case 5130': 105, 'Case 5140': 117, 'Case 5150': 132, 'Case 5220': 88, 'Case 5230': 100, 'Case 5240': 111, 'Case 5250': 124, 'Case 7110': 144, 'Case 7120': 166, 'Case 7130': 188, 'Case 7140': 216, 'Case 7150': 238, 'Case 7210': 144, 'Case 7220': 172, 'Case 7230': 188, 'Case 7240': 216, 'Case 7250': 238, 'Case 8910': 150, 'Case 8920': 172, 'Case 8930': 200, 'Case 8940': 227, 'Case 8950': 250, 'Case 9110': 200, 'Case 9130': 220, 'Case 9150': 280, 'Case 9170': 335, 'Case 9180': 375, 'Case 9190': 525, 'Case 9210': 200, 'Case 9230': 235, 'Case 9240': 235, 'Case 9250': 300, 'Case 9260': 300, 'Case 9270': 335, 'Case 9280': 375, 'Case 9310': 205, 'Case 9330': 240, 'Case 9350': 310, 'Case 9370': 360, 'Case 9380': 400, 'Case 9390': 425, 'Case C100': 100, 'Case CX50': 53, 'Case CX60': 64, 'Case CX70': 73, 'Case CX80': 84, 'Case CX90': 90, 'Case DX23': 23, 'Case DX25': 25, 'Case DX26': 26, 'Case DX29': 29, 'Case DX31': 31, 'Case DX33': 33, 'Case DX34': 35, 'Case DX35': 35, 'Case DX40': 40, 'Case DX45': 45, 'Case DX60': 60, 'Case JX55': 58, 'Case JX60': 55, 'Case JX65': 65, 'Case JX70': 62, 'Case JX75': 75, 'Case JX80': 72, 'Case JX85': 77, 'Case JX90': 82, 'Case JX95': 93, 'Case PJ55': 55, 'Case PJ65': 65, 'Case PJ75': 75, 'Case 300': 30, 'Case 301': 30, 'Case 302': 30, 'Case 310': 32, 'Case 311': 32, 'Case 312': nan, 'Case 350': 46, 'Case 351': 46, 'Case 400': 55, 'Case 412': 55, 'Case 430': 37, 'Case 431': 37, 'Case 440': 36, 'Case 441': 36, 'Case 470': 37, 'Case 500': 61, 'Case 530': 45, 'Case 570': 43, 'Case 600': nan, 'Case 610': 62, 'Case 630': 54, 'Case 700': 56, 'Case 730': 62, 'Case 731': 62, 'Case 741': 64, 'Case 770': 62, 'Case 810': 80, 'Case 830': 73, 'Case 870': 78, 'Case 885': 84, 'Case 930': 89, 'Case 970': 95, 'Case 990': 58, 'Case 995': 104, 'Case 234': 16, 'Case 235': 18, 'Case 244': 20, 'Case 245': 21, 'Case 254': 23, 'Case 255': 24, 'Case 265': 27, 'Case 275': 31, 'Case 385': 43, 'Case 395': 46, 'Case 485': 53, 'Case 495': 53, 'Case 585': 60, 'Case 595': 60, 'Case 685': 73, 'Case 695': 72, 'Case 785': 77, 'Case 795': 77, 'Case 895': 84, 'Case 985': 90, 'Case C42': 42, 'Case C48': 48, 'Case C50': 53, 'Case C55': 55, 'Case C60': 64, 'Case C64': 64, 'Case C70': 73, 'Case C80': 84, 'Case C90': 90, 'Case D25': 25, 'Case D29': 29, 'Case D33': 33, 'Case D35': 35, 'Case D40': 40, 'Case D45': 45, 'Claas Nexos 240 VL': 101, 'Claas Xerion 3300': 335, 'Claas Xerion 3800': 379, 'Claas Xerion 4000': 419, 'Claas Xerion 4200': 458, 'Claas Xerion 4500': 449, 'Claas Xerion 5000': 487, 'Claas Nexos 240 F': 101, 'Claas 3300 Trac': 335, 'Claas Arion 410': 90, 'Claas Arion 420': 100, 'Claas Arion 430': 110, 'Claas Arion 440': 115, 'Claas Arion 450': 125, 'Claas Arion 460': 135, 'Claas Arion 510': 110, 'Claas Arion 520': 120, 'Claas Arion 530': 130, 'Claas Arion 540': 135, 'Claas Arion 610': 120, 'Claas Arion 620': 135, 'Claas Arion 630': 145, 'Claas Arion 640': 155, 'Claas Arion 650': 182, 'Claas Axion 660': 182, 'Claas Arion 660': 182, 'Claas Axion 800': 193, 'Claas Axion 810': 200, 'Claas Axion 820': 215, 'Claas Axion 830': 215, 'Claas Axion 840': 230, 'Claas Axion 850': 245, 'Claas Axion 860': 250, 'Claas Axion 870': 270, 'Claas Axion 880': 265, 'Claas Axion 920': 311, 'Claas Axion 930': 340, 'Claas Axion 940': 370, 'Claas Axion 950': 399, 'Claas Axion 960': 433, 'Claas Elios 210': 72, 'Claas Elios 220': 88, 'Claas Elios 230': 88, 'Claas Elios 240': 96, 'Claas Talos 120': 46, 'Claas Talos 130': 55, 'Claas Talos 210': 69, 'Claas Talos 220': 76, 'Claas Talos 230': 87, 'Claas Talos 240': 93, 'Claas Nexos 220': 83, 'Claas Nexos 230': 87, 'Claas Nexos 250': 110, 'Claas Nexos 210': 71, 'Claas Axos 310': 75, 'Claas Axos 320': 87, 'Claas Axos 330': 92, 'Claas Axos 340': 102, 'Claas Ares 547': 88, 'Claas Ares 557': 98, 'Claas Ares 567': 108, 'Claas Ares 577': 118, 'Claas Ares 617': 108, 'Claas Ares 657': 123, 'Claas Ares 697': 138, 'Claas 2500': 265, 'Claas 3000': 315, 'Claas 65E': 310, 'Claas 75E': 340, 'Claas 85E': 375, 'Claas 95E': 410, 'Claas 217': 56, 'Claas 227': 68, 'Claas 237': 79, 'Claas 257': 90, 'Claas 267': 101, 'Claas 426': 75, 'Claas 436': 84, 'Claas 446': 92, 'Claas 456': 102, 'Claas 546': 96, 'Claas 556': 104, 'Claas 566': 114, 'Claas 616': 115, 'Claas 656': 132, 'Claas 696': 146, 'Claas 816': 164, 'Claas 826': 181, 'Claas 836': 205, 'Claas 926': 232, 'Claas 936': 253, 'Claas 946': 282, 'Claas 35': 210, 'Claas 45': 240, 'Claas 55': 250, 'Daedong  LK3054': 28, 'Daedong  LK4504': 46, 'Daedong  LX500L': nan, 'Daedong  DK90C': 92, 'Daedong  DK451': 45, 'Daedong  DK501': 50, 'Daedong  DK551': 55, 'Daedong  DK561': 64, 'Daedong  DK751': 72, 'Daedong  DK752': 72, 'Daedong  DK901': 90, 'Daedong  DK902': 90, 'Daedong  FX651': 59, 'Daedong  FX751': 67, 'Daedong  CK20': 21, 'Daedong  CK30': 30, 'Daedong  DK35': 35, 'Daedong  DK40': 40, 'Daedong  DK45': 45, 'Daedong  DK50': 50, 'Daedong  DK65': 65, 'Daedong  DK75': 75, 'Daedong  DK80': 82, 'Daedong  DK90': 92, 'Daedong  EX35': 38, 'Daedong  EX40': 41, 'Daedong  EX45': 45, 'Daedong  EX50': 50, 'Deutz Fahr Agroplus F 310 ecoline': 61, 'Deutz Fahr Agroplus 410 ecoline': 84, 'Deutz Fahr Agrotron 100 MK3': 95, 'Deutz Fahr Agrotron 105 MK3': 100, 'Deutz Fahr Agrotron 106 MK3': 102, 'Deutz Fahr Agrotron 110 MK3': 107, 'Deutz Fahr Agrotron 115 MK3': 117, 'Deutz Fahr Agrotron 120 MK3': 125, 'Deutz Fahr Agrotron 135 MK3': 140, 'Deutz Fahr Agrotron 150 MK3': 150, 'Deutz Fahr Agrotron 165 MK3': 160, 'Deutz Fahr Agrotron 175 MK3': 175, 'Deutz Fahr Agrotron 200 MK3': 200, 'Deutz Fahr Agrotron 205 MK3': 196, 'Deutz Fahr Agrotron 230 MK3': 230, 'Deutz Fahr Agrotron 260 MK3': 260, 'Deutz Fahr Agrotron 80 MK3': 75, 'Deutz Fahr Agrotron 85 MK3': 82, 'Deutz Fahr Agrotron 90 MK3': 88, 'Deutz Fahr Agrotron 150.7': 163, 'Deutz Fahr Agrotron 165.7': 177, 'Deutz Fahr Agrotron 180.7': 179, 'Deutz Fahr Agroplus F430': 104, 'Deutz Fahr 4046E Keyline': 44, 'Deutz Fahr 4050E Keyline': 49, 'Deutz Fahr 4055E Keyline': 54, 'Deutz Fahr 420 Profiline': 93, 'Deutz Fahr Agroplus 315': 71, 'Deutz Fahr Agroplus 320': 80, 'Deutz Fahr Agroplus 410': 83, 'Deutz Fahr Agroplus 420': 93, 'Deutz Fahr Agrotron 105': 81, 'Deutz Fahr Agrotron 106': 100, 'Deutz Fahr Agrotron 110': 105, 'Deutz Fahr Agrotron 115': 116, 'Deutz Fahr Agrotron 120': 128, 'Deutz Fahr Agrotron 130': 139, 'Deutz Fahr Agrotron 135': 135, 'Deutz Fahr Agrotron 150': 158, 'Deutz Fahr Agrotron 160': 160, 'Deutz Fahr Agrotron 175': 175, 'Deutz Fahr Agrotron 200': 200, 'Deutz Fahr Agrotron 230': 230, 'Deutz Fahr Agrofarm 115': 108, 'Deutz Fahr Agrofarm 100': 94, 'Deutz Fahr Agrofarm 420': 97, 'Deutz Fahr Agrofarm 95C': 160, 'Deutz Fahr Agrokid 210': 38, 'Deutz Fahr Agrokid 220': 42, 'Deutz Fahr Agrokid 230': 49, 'Deutz Fahr Agrolux 410': 73, 'Deutz Fahr Agrolux 310': 62, 'Deutz Fahr Agrolux 320': 72, 'Deutz Fahr Agrotron 80': 75, 'Deutz Fahr Agrotron 90': 88, 'Deutz Fahr Intrac 6.05': 98, 'Deutz Fahr Intrac 6.30': 126, 'Deutz Fahr Intrac 6.60': 150, 'Deutz Fahr Intrac 2002': 50, 'Deutz Fahr Intrac 2003': 59, 'Deutz Fahr Intrac 2004': 70, 'Deutz Fahr Intrac 2005': 84, 'Deutz Fahr Intrac 2006': 116, 'Deutz Fahr 6120.4 TTV': 114, 'Deutz Fahr 6130.4 TTV': 124, 'Deutz Fahr 6140.4 TTV': 130, 'Deutz Fahr 6150.4 TTV': 137, 'Deutz Fahr 6160.4 TTV': 155, 'Deutz Fahr Agrokid 25': 24, 'Deutz Fahr Agrokid 30': 34, 'Deutz Fahr Agrokid 35': 34, 'Deutz Fahr Agrokid 40': 40, 'Deutz Fahr Agrokid 45': 41, 'Deutz Fahr Agrokid 50': 47, 'Deutz Fahr Agrolux 65': 62, 'Deutz Fahr Agrolux 75': 72, 'Deutz Fahr 6120 TTV': 123, 'Deutz Fahr 6125 TTV': 135, 'Deutz Fahr 6155 TTV': 154, 'Deutz Fahr 6160 TTV': 155, 'Deutz Fahr 6165 TTV': 162, 'Deutz Fahr 6175 TTV': 174, 'Deutz Fahr 6180 TTV': 165, 'Deutz Fahr 6185 TTV': 185, 'Deutz Fahr 6190 TTV': 165, 'Deutz Fahr 6205 TTV': 204, 'Deutz Fahr 6215 TTV': 209, 'Deutz Fahr 7210 TTV': 186, 'Deutz Fahr 7230 TTV': 204, 'Deutz Fahr 7250 TTV': 236, 'Deutz Fahr 8280 TTV': 268, 'Deutz Fahr 9290 TTV': 277, 'Deutz Fahr 9310 TTV': 296, 'Deutz Fahr 9340 TTV': 316, 'Deutz Fahr TTV 1130': 125, 'Deutz Fahr TTV 1145': 140, 'Deutz Fahr TTV 1160': 150, 'Deutz Fahr 4080.4E': 78, 'Deutz Fahr 

In [17]:
df['new_MakeDescr'] = new_MakeDescr_list
df['new_ModelDescr'] = new_ModelDescr_list
df

,ReportingPeriod,SourceInstanceCd,ConsolidationCd,BusinessUnitDesc,AgreementNbr,AgreementClassificationRefCd,AgreementStatusRefCd,Agreement_Exposure_EUR,Agreement_NetPrincipalBalanceAmt_EUR,FinanceAgreementLineNbr,...,model_match4,HPmatch1,asset_type_match,Attribution factor,Total fuel usage (L of Diesel),GHG emissions (Kg CO2-eq.),Attributable GHG (Kg CO2-eq.),Attributable GHG (tons CO2-eq.),new_MakeDescr,new_ModelDescr
0,M202110,INFAU,AGAAU,Food & Agriculture,016-0034538-004,BLO,BOOKED,32180.796374,32180.796374,016-0034538-004_488868,...,NaN,236.0,+140 HP Tractor,0.747473,11469.604000,32000.195160,23919.292880,23.919293,Deutz Fahr,7250 TTV
1,M202110,INFAU,AGAAU,Food & Agriculture,016-0038548-001,BLO,BOOKED,109052.852056,109052.852056,016-0038548-001_529392,...,NaN,178.0,+140 HP Tractor,0.882717,11469.604000,32000.195160,28247.108678,28.247109,Claas,N 180a
2,M202110,INFAU,AGAAU,Food & Agriculture,016-0044635-001,BLO,BOOKED,28089.070897,28089.070897,016-0044635-001_477195,...,NaN,NaN,Tractor,0.687591,4536.946962,12658.082024,8703.586458,8.703586,McCormick,MTX110
3,M202110,INFAU,AGAAU,Food & Agriculture,016-0054437-001,BLO,BOOKED,24748.760117,24748.760117,016-0054437-001_501417,...,NaN,157.0,+140 HP Tractor,0.786592,11469.604000,32000.195160,25171.111840,25.171112,Deutz Fahr,6160 TTV
4,M202110,INFAU,AGAAU,Food & Agriculture,016-0061278-003,BLO,BOOKED,20454.509550,20371.246358,016-0061278-003_314895,...,NaN,125.0,100-139 HP Tractor,0.357392,3860.142000,10769.796180,3849.044157,3.849044,Case,1255 XL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4866,M202110,INFAU,AGANZ,Food & Agriculture,282-0454379-001,BLO,BOOKED,42681.457769,42681.457769,282-0454379-001_482101,...,NaN,130.0,100-139 HP Tractor,0.636878,3860.142000,10769.796180,6859.041024,6.859041,John Deere,7R 210
4867,M202110,INFAU,AGANZ,Food & Agriculture,282-0458168-001,BLO,BOOKED,37816.362965,37816.362965,282-0458168-001_512843,...,NaN,130.0,100-139 HP Tractor,0.594692,3860.142000,10769.796180,6404.709724,6.404710,John Deere,6130R
4868,M202110,INFAU,AGANZ,Food & Agriculture,282-0498175-001,BLO,BOOKED,150660.428466,150660.428466,282-0498175-001_510073,...,2020,215.0,+140 HP Tractor,1.000000,11469.604000,32000.195160,32000.195160,32.000195,John Deere,6215 RC
4869,M202110,INFAU,AGANZ,Food & Agriculture,282-0514496-001,BLO,BOOKED,95017.877370,95017.877370,282-0514496-001_530507,...,NaN,155.0,+140 HP Tractor,0.821387,11469.604000,32000.195160,26284.558271,26.284558,John Deere,6215 RC
4870,M202110,INFAU,AGANZ,Food & Agriculture,282-0527441-001,BLO,BOOKED,35372.722236,35372.722236,282-0527441-001_526297,...,NaN,210.0,+140 HP Tractor,0.780487,11469.604000,32000.195160,24975.735042,24.975735,John Deere,1026R

In [18]:
df['new_CombinedColumn'] = df['new_MakeDescr'].astype(str) + ' ' + df['new_ModelDescr'].astype(str)
df['new_mapped_HP'] = (df['new_CombinedColumn']).map(dictionary)
df

,ReportingPeriod,SourceInstanceCd,ConsolidationCd,BusinessUnitDesc,AgreementNbr,AgreementClassificationRefCd,AgreementStatusRefCd,Agreement_Exposure_EUR,Agreement_NetPrincipalBalanceAmt_EUR,FinanceAgreementLineNbr,...,asset_type_match,Attribution factor,Total fuel usage (L of Diesel),GHG emissions (Kg CO2-eq.),Attributable GHG (Kg CO2-eq.),Attributable GHG (tons CO2-eq.),new_MakeDescr,new_ModelDescr,new_CombinedColumn,new_mapped_HP
0,M202110,INFAU,AGAAU,Food & Agriculture,016-0034538-004,BLO,BOOKED,32180.796374,32180.796374,016-0034538-004_488868,...,+140 HP Tractor,0.747473,11469.604000,32000.195160,23919.292880,23.919293,Deutz Fahr,7250 TTV,Deutz Fahr 7250 TTV,236
1,M202110,INFAU,AGAAU,Food & Agriculture,016-0038548-001,BLO,BOOKED,109052.852056,109052.852056,016-0038548-001_529392,...,+140 HP Tractor,0.882717,11469.604000,32000.195160,28247.108678,28.247109,Claas,N 180a,Claas N 180a,NaN
2,M202110,INFAU,AGAAU,Food & Agriculture,016-0044635-001,BLO,BOOKED,28089.070897,28089.070897,016-0044635-001_477195,...,Tractor,0.687591,4536.946962,12658.082024,8703.586458,8.703586,McCormick,MTX110,McCormick MTX110,116
3,M202110,INFAU,AGAAU,Food & Agriculture,016-0054437-001,BLO,BOOKED,24748.760117,24748.760117,016-0054437-001_501417,...,+140 HP Tractor,0.786592,11469.604000,32000.195160,25171.111840,25.171112,Deutz Fahr,6160 TTV,Deutz Fahr 6160 TTV,155
4,M202110,INFAU,AGAAU,Food & Agriculture,016-0061278-003,BLO,BOOKED,20454.509550,20371.246358,016-0061278-003_314895,...,100-139 HP Tractor,0.357392,3860.142000,10769.796180,3849.044157,3.849044,Case,1255 XL,Case 1255 XL,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4866,M202110,INFAU,AGANZ,Food & Agriculture,282-0454379-001,BLO,BOOKED,42681.457769,42681.457769,282-0454379-001_482101,...,100-139 HP Tractor,0.636878,3860.142000,10769.796180,6859.041024,6.859041,John Deere,7R 210,John Deere 7R 210,210
4867,M202110,INFAU,AGANZ,Food & Agriculture,282-0458168-001,BLO,BOOKED,37816.362965,37816.362965,282-0458168-001_512843,...,100-139 HP Tractor,0.594692,3860.142000,10769.796180,6404.709724,6.404710,John Deere,6130R,John Deere 6130R,130
4868,M202110,INFAU,AGANZ,Food & Agriculture,282-0498175-001,BLO,BOOKED,150660.428466,150660.428466,282-0498175-001_510073,...,+140 HP Tractor,1.000000,11469.604000,32000.195160,32000.195160,32.000195,John Deere,6215 RC,John Deere 6215 RC,NaN
4869,M202110,INFAU,AGANZ,Food & Agriculture,282-0514496-001,BLO,BOOKED,95017.877370,95017.877370,282-0514496-001_530507,...,+140 HP Tractor,0.821387,11469.604000,32000.195160,26284.558271,26.284558,John Deere,6215 RC,John Deere 6215 RC,NaN
4870,M202110,INFAU,AGANZ,Food & Agriculture,282-0527441-001,BLO,BOOKED,35372.722236,35372.722236,282-0527441-001_526297,...,+140 HP Tractor,0.780487,11469.604000,32000.195160,24975.735042,24.975735,John Deere,1026R,John Deere 1026R,25

In [41]:
df['CombinedColumn'] = df['MakeDescr'].astype(str) + ' ' + df['ModelDescr'].astype(str)

In [42]:
df_combined_list = df['CombinedColumn'].tolist()
data_combined_list = data['CombinedColumn'].tolist()

In [54]:
string_list = data_combined_list
new_combined_Jaccard_list = []

for i in range(len(df_combined_list)):
    if isinstance(df_combined_list[i], str):
        target_string = df_combined_list[i]
        most_similar = find_most_similar_string_Jaccard(target_string, string_list)
        new_combined_Jaccard_list.append(most_similar)
    else:
        new_combined_Jaccard_list.append(None)  # Handle non-string values

print(new_combined_Jaccard_list)

['Deutz Fahr 7250 TTV', 'AGCO Allis 8610', 'McCormick MTX110', 'Deutz Fahr 6160 TTV', 'Case MXU125', 'John Deere 4760', 'Claas Nexos 220', 'Case Puma 165', 'Valtra T191', 'Claas 65E', 'Hitachi NTX360', 'Case MXM140', 'Deutz Fahr Agroplus 410', 'Hitachi NTX360', 'Case STX375', 'New Holland TG285', 'Kubota M4700', 'Versatile 405', 'Case JX75', 'New Holland T7.235', 'Deutz Fahr DX 4.30', 'Deutz Fahr Agroplus F430', 'New Holland T9040', 'Massey Ferguson 4445', 'Massey Ferguson 5475', 'Massey Ferguson 5465', 'Case CS 48', 'John Deere 8R 280', 'Kubota M7950HC', 'Antonio Carraro SRH 9800', 'Valtra 6400', 'John Deere 9520T', 'John Deere 3640', 'John Deere 1026R', 'John Deere 8230', 'Valtra M120', 'John Deere 6125R', 'Case 9330', 'John Deere 3045R', 'Claas Elios 230', 'John Deere AWD', 'Pasquali 440', 'Fendt 822', 'Massey Ferguson 6614', 'New Holland T8030', 'John Deere 8345R', 'John Deere 7R 210', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.435', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.435', 'New Holland T8.320', 'Case Maxxum 125', 'AGCO ST22A', 'Fendt 309', 'Kubota M4030SU', 'Kubota M4030SU', 'John Deere 6140M', 'Claas 456', 'Case MXU125', 'John Deere 5038D', 'Case MX240', 'Case MXM130', 'Valtra 6400', 'Case Magnum 260', 'Case Farmall 60A', 'Case STX450', 'John Deere 9570R', 'John Deere 6930', 'AGCO ST30', 'New Holland T8.360', 'Case MXU115', 'TYM T700', 'Valtra N101', 'Case MXM120', 'John Deere 6140R', 'Case Maxxum 110', 'John Deere 7930', 'Mahindra mForce 100', 'Farmtrac FT 30', 'McCormick CX85', 'Case MX90C', 'Antonio Carraro TTR 4400', 'John Deere 8120', 'Zetor 4522', 'Versatile 405', 'McCormick CX100', 'Claas 3000', 'New Holland T8.390', 'Case Magnum 275', 'Antonio Carraro TTR 4400', 'Case Farmall 60A', 'Case Farmall 60A', 'John Deere 9460R', 'Mahindra 2540', 'Apollo 954', 'McCormick F95', 'Case MXU125', 'Mahindra 4565', 'Kubota KL380', 'New Holland TC24DA', 'Case C55', 'Apollo 354', 'New Holland T7.210', 'Farmtrac 60', 'New Holland TL100A', 'Apollo 854', 'Apollo 454', 'Massey Ferguson 6130', 'AGCO Allis 9435', 'Apollo 254', 'Apollo 454', 'Apollo 354', 'John Deere 6910', 'Hurlimann H-355', 'John Deere 2355', 'Farmtrac 270DTC', 'Apollo 454', 'John Deere 3038R', 'Kubota M108 DC', 'Kubota M108 DC', 'Kubota M108 DC', 'Kubota M108 DC', 'Kubota M108 DC', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Kubota M108', 'Apollo 454', 'Apollo 454', 'AGCO RT145', 'New Holland Boomer 2035', 'New Holland T5070', 'New Holland TS100A', 'McCormick MTX135', 'Apollo 454', 'Apollo 354', 'Farmtrac 270DTC', 'Farmtrac FT 30', 'Case Farmall 100N', 'Solis 110', 'Apollo 454', 'Massey Ferguson 3435', 'Massey Ferguson 4270', 'Apollo 454', 'Apollo 854', 'Claas Arion 620', 'Fendt Farmer 412 Vario', 'Fendt 305 LS', 'New Holland T7.185', 'Apollo 954', 'Kubota M108 DC', 'Kubota M100GX', 'Kubota M135GX', 'Kubota M108 DC', 'Kubota M100GX', 'Kubota M100GX', 'Kubota M108 DC', 'Kubota M100GX', 'Kubota M135', 'Kubota M135', 'Deutz Fahr Agroplus 315', 'Deutz Fahr Agroplus 315', 'Apollo 954', 'Apollo 454', 'Apollo 454', 'Case 500', 'Farmtrac 360DTC', 'New Holland T7.185', 'Farmtrac 360DTC', 'Apollo 354', 'Kubota M108 DC', 'Kubota M108 DC', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Apollo 454', 'Massey Ferguson 4445', 'John Deere 6195R', 'John Deere 755', 'McCormick MTX135', 'John Deere 8R 310', 'McCormick MC90', 'Deutz Fahr 6155', 'New Holland T4.55', 'Apollo 454', 'Fendt 716', 'McCormick CX85', 'Fendt 936', 'John Deere 9460R', 'John Deere 6145R', 'Apollo 454', 'Apollo 254', 'Apollo 354', 'Apollo 354', 'Apollo 454', 'Apollo 454', 'Apollo 454', 'John Deere 3640', 'Case DX60', 'Apollo 454', 'John Deere 6125M', 'John Deere 6115R', 'Apollo 454', 'Valtra N124', 'Case JX70', 'Apollo 454', 'Apollo 354', 'New Holland T6080 Elite', 'Apollo 454', 'Apollo 454', 'Antonio Carraro TRX 7800S', 'Apollo 454', 'McCormick MC90', 'Apollo 354', 'Apollo 454', 'Case STX330', 'Claas Axos 340', 'Apollo 354', 'Apollo 454', 'Case 600', 'John Deere 8360RT', 'John Deere 8360R', 'Kubota M7.171', 'Apollo 454', 'Apollo 454', 'Case Maxxum 120', 'Apollo 954', 'New Holland T5.95', 'Apollo 454', 'New Holland T7040', 'John Deere 2640', 'Apollo 354', 'Apollo 354', 'Landini DT 7000', 'Apollo 454', 'Landini Rex 75', 'Apollo 954', 'Landini 6860', 'Apollo 454', 'Apollo 454', 'Apollo 454', 'Claas Axion 840', 'Apollo 354', 'John Deere 8245R', 'Apollo 354', 'John Deere 7R 210', 'John Deere 6125R', 'John Deere 4720', 'Case Magnum 340', 'New Holland TS100A', 'John Deere 1830', 'John Deere AWD', 'John Deere 6115M', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'John Deere 6125M', 'Apollo 454', 'Apollo 254', 'Apollo 454', 'Apollo 454', 'McCormick X50.40m', 'Apollo 454', 'Apollo 454', 'Apollo 454', 'Apollo 354', 'Kubota M7950HC', 'Carraro 454DT', 'McCormick C100 Max', 'Claas Axion 950', 'Claas Axion 950', 'Apollo 354', 'John Deere 8300', 'Kubota M7950HC', 'Apollo 454', 'Apollo 454', 'Apollo 454', 'Landini 75', 'Valtra N134', 'Landini 6860', 'Apollo 454', 'Apollo 1104', 'Apollo 454', 'Apollo 454', 'John Deere 7930', 'Landini 75', 'Landini 5-100D', 'Apollo 454', 'Apollo 454', 'Apollo 454', 'John Deere 6130R', 'Landini 105', 'New Holland T7.170', 'Mahindra 6000', 'Mahindra 6530', 'Case CVX 120', 'Apollo 454', 'Apollo 454', 'John Deere 8300T', 'New Holland TM130', 'Daedong  DK65', 'Case Puma 115', 'Apollo 454', 'John Deere 1830', 'Landini Rex 90', 'Landini Evolution 6865', 'Landini 5-100D', 'Landini 7856', 'Landini Technofarm 85', 'Landini  8865 super', 'Landini 7856', 'Landini Legend 145 TDI', 'Landini  8865', 'Landini  8865', 'Landini 120', 'Landini 10000', 'Landini  8865', 'Landini 8880', 'Landini  8865', 'Landini  8865', 'Landini 4-105', 'Landini Rex 120', 'Kubota L1-275', 'Case Farmall 55A', 'Landini Rex 95', 'Landini 4-105', 'Landini 7856', 'Landini Rex 90', 'Landini 7856', 'Landini Powerfarm 100', 'Landini 8560F', 'Landini 165', 'Landini Powerfarm 75', 'Landini  8865 super', 'Case CX50', 'Claas Arion 620', 'Claas Arion 410', 'AGCO Allis 9150', 'Case MX80C', 'Claas Arion 620', 'Claas 2500', 'Claas Axion 950', 'Claas Arion 620', 'Claas Arion 620', 'Case Farmall 130A', 'Claas Axos 340', 'Claas Arion 630', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 620', 'Claas 3000', 'Claas Arion 530', 'Claas Arion 530', 'AGCO Allis 4660', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 410', 'Claas Arion 630', 'Claas Arion 460', 'Claas Axos 320', 'Claas Arion 610', 'Claas Arion 510', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'AGCO Allis 4650', 'AGCO Allis 9130', 'AGCO Allis 7630', 'Claas Arion 430', 'Claas Arion 410', 'AGCO Allis 5650', 'AGCO Allis 7630', 'Case Farmall 60A', 'AGCO Allis 4660', 'Claas Arion 620', 'Claas Arion 450', 'Claas Arion 440', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 840', 'Claas Arion 430', 'Claas Arion 620', 'Claas Axion 840', 'Claas Axos 340', 'Case Farmall 140A', 'AGCO Allis 4660', 'Claas Arion 460', 'AGCO Allis 8630', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 870', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 530', 'Claas Arion 620', 'AGCO Allis 9130', 'AGCO Allis 8610', 'AGCO Allis 5680', 'AGCO Allis 9150', 'Pasquali ORION 7.75', 'Claas Arion 410', 'Claas Arion 460', 'Case Farmall 60A', 'Case STX430', 'Pasquali EOS 5.50AR', 'AGCO Allis 4660', 'Pasquali VANTH 5.30', 'Claas Arion 660', 'AGCO Allis 5650', 'AGCO Allis 8630', 'Claas Arion 420', 'Case MX80C', 'Claas Arion 650', 'Claas Arion 460', 'AGCO RT140A', 'Mahindra 2540', 'Claas Arion 630', 'AGCO Allis 5680', 'Claas Arion 650', 'AGCO Allis 4660', 'Claas Arion 530', 'Claas 2500', 'Case Farmall 120A', 'Case Farmall 120A', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 520', 'Claas Arion 620', 'Claas Axion 800', 'Claas Arion 620', 'Claas 446', 'Claas Axion 870', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 430', 'AGCO Allis 9130', 'Claas Axion 800', 'Claas 45', 'Claas Axion 950', 'Claas Axos 340', 'Claas Arion 620', 'Claas Arion 430', 'Claas 556', 'Claas Axos 340', 'Claas Arion 610', 'Case STX530', 'AGCO Allis 4650', 'AGCO Allis 7630', 'Claas Arion 620', 'Claas Arion 620', 'Case MX180', 'Case Farmall 40A', 'Claas Axion 830', 'Claas Arion 530', 'Claas Arion 610', 'Claas Axos 340', 'Deutz Fahr Agrotron 90', 'Case Farmall 35A', 'Claas Arion 520', 'Claas Arion 620', 'Case Farmall 120A', 'Claas 3000', 'Claas 2500', 'AGCO Allis 9130', 'Claas Arion 460', 'Claas Axion 870', 'Claas Axion 810', 'Pasquali ORION 7.85', 'Pasquali ORION 7.85', 'Mahindra 4010', 'Claas Arion 650', 'Claas Arion 620', 'Claas 3000', 'Claas 3000', 'Claas Arion 430', 'Claas Arion 620', 'Case STX380', 'Case Farmall 120A', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 430', 'Claas Arion 620', 'Case CX80', 'Claas Arion 650', 'Claas Axos 340', 'Claas 3000', 'Claas Arion 460', 'Claas 2500', 'AGCO Allis 8630', 'Claas Arion 630', 'Claas 3000', 'Claas 3000', 'John Deere 6140M', 'John Deere 5065M', 'Claas Arion 620', 'Pasquali EOS 5.50AR', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 620', 'Claas Arion 620', 'AGCO Allis 8630', 'Case Farmall 130A', 'Case Farmall 130A', 'Case Farmall 120A', 'Pasquali EOS 5.50AR', 'AGCO Allis 4660', 'Claas Arion 620', 'AGCO Allis 4660', 'Claas Axos 340', 'Claas Arion 630', 'Claas 2500', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 620', 'Case Farmall 120A', 'AGCO Allis 9130', 'LS Brasil R60', 'Claas Axos 340', 'AGCO Allis 4660', 'Pasquali ORION 7.75', 'New Holland T7.235', 'Claas Axos 320', 'AGCO Allis 7630', 'Claas 3000', 'Case STX430', 'Claas Arion 610', 'Claas Axion 930', 'AGCO Allis 8630', 'Antonio Carraro TTR 4400', 'AGCO Allis 8630', 'Claas 3000', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 460', 'Claas Arion 460', 'Claas Arion 620', 'New Holland TL70A', 'Claas Arion 410', 'Claas Arion 620', 'AGCO Allis 5650', 'Claas Arion 620', 'Claas Axos 330', 'Claas Arion 420', 'New Holland TS100A', 'Claas 3000', 'Claas Arion 410', 'Claas Axion 840', 'Case Farmall 60A', 'Landini Mistral America 40', 'Claas Axion 850', 'Claas Arion 620', 'Claas Arion 430', 'Claas Arion 620', 'Claas Talos 220', 'Case Farmall 130A', 'AGCO Allis 9130', 'Claas Axos 340', 'Case Farmall 60A', 'Claas Arion 620', 'Claas Arion 530', 'Claas Axos 340', 'AGCO Allis 9130', 'Case Farmall 60A', 'Claas Arion 620', 'Claas Arion 620', 'Case CX80', 'Claas 2500', 'Claas Arion 430', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 620', 'Case MX180', 'AGCO Allis 9130', 'Claas Arion 620', 'Claas Arion 610', 'Deutz Fahr K420', 'AGCO Allis 8630', 'Claas Axos 340', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 460', 'Case Farmall 60A', 'Claas Arion 430', 'AGCO Allis 9130', 'AGCO Allis 4660', 'Case STX380', 'Claas Arion 630', 'Claas Arion 420', 'Claas 65E', 'Claas Axion 870', 'Case MXU125', 'Claas Arion 430', 'Claas Arion 460', 'Claas Arion 430', 'Claas 3000', 'Claas Arion 420', 'Claas Arion 410', 'Claas Arion 460', 'Claas Axos 330', 'Case Farmall 60A', 'Claas Arion 620', 'New Holland TD95D', 'AGCO Allis 9130', 'Claas Arion 430', 'Claas Arion 620', 'Claas Axion 820', 'Case MXU135', 'AGCO Allis 9150', 'Case MX90C', 'Claas Arion 440', 'AGCO Allis 9130', 'Claas Arion 620', 'Claas Axos 320', 'Claas Arion 620', 'Claas Axos 320', 'Claas Arion 620', 'Deutz Fahr 5100', 'Claas Arion 410', 'Claas Arion 430', 'Fendt 712', 'Claas Axos 320', 'AGCO Allis 8630', 'Claas Axos 320', 'Claas Axos 320', 'Claas 446', 'AGCO RT100A', 'Claas Arion 620', 'AGCO Allis 9130', 'Claas Axos 330', 'Claas Arion 410', 'Claas Arion 620', 'Antonio Carraro TTR 4400', 'Case STX430', 'Claas Arion 620', 'AGCO DT205B', 'Claas Axion 870', 'Claas 2500', 'Claas Arion 620', 'AGCO Allis 9150', 'Claas Arion 610', 'Claas Arion 620', 'Claas Arion 460', 'Claas Arion 460', 'Claas Arion 460', 'Claas Arion 460', 'Claas Arion 460', 'Claas Arion 460', 'Claas Axos 340', 'Claas Arion 650', 'Claas Arion 620', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 870', 'Case Maxxum 110', 'Claas 616', 'Claas Arion 410', 'AGCO RT140A', 'Claas Arion 460', 'Claas Arion 620', 'AGCO Allis 9130', 'Massey Ferguson 3435', 'Claas Axion 870', 'Case Farmall 95C', 'Claas Arion 460', 'Claas Arion 410', 'Claas Arion 620', 'AGCO RT140A', 'Case MXM130', 'Claas Arion 620', 'Antonio Carraro TRX 9800', 'Claas 3000', 'Claas Arion 610', 'Claas Arion 650', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 430', 'Claas Axos 330', 'Claas Arion 620', 'Claas 2500', 'AGCO RT140A', 'Claas 2500', 'Claas Arion 610', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 460', 'Claas 3000', 'AGCO Allis 4660', 'Case CVX 150', 'Claas Arion 430', 'AGCO Allis 4660', 'Claas Arion 620', 'Case MXU135', 'Claas Arion 430', 'Claas Axos 340', 'Claas Axos 340', 'Claas Arion 620', 'Claas Arion 440', 'Claas Arion 430', 'Claas Arion 610', 'Claas Arion 410', 'AGCO RT140A', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 430', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 610', 'Landini Mistral America 40', 'Claas Arion 430', 'Claas Xerion 3300', 'Claas 446', 'Claas Axos 340', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 850', 'Claas Arion 460', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 460', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 620', 'Claas Arion 430', 'Claas 446', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 410', 'Claas Axion 950', 'Claas Axos 340', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 410', 'Claas 2500', 'Claas Arion 620', 'Case MX180', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 410', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 650', 'New Holland TL100A', 'Case Magnum 180', 'Claas Nexos 240 F', 'Claas Nexos 240 F', 'Case MXU100', 'Claas Nexos 240 F', 'Claas Nexos 240 F', 'Claas Nexos 240 F', 'Claas Nexos 240 F', 'Claas Nexos 240 F', 'Claas Nexos 240 F', 'Claas Nexos 240 F', 'Claas Nexos 240 F', 'Claas Nexos 240 VL', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'New Holland TD5050HC', 'Claas 2500', 'Claas Arion 630', 'Claas Arion 650', 'Claas Axion 850', 'Claas Arion 620', 'Claas Arion 630', 'Antonio Carraro TRX 10400', 'Claas Axion 830', 'Claas 2500', 'JCB Fastrac 4220', 'JCB Fastrac 4220', 'Claas Arion 650', 'Claas Axion 830', 'AGCO Allis 7630', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 610', 'Claas 3000', 'Pasquali EOS 5.50AR', 'Case Farmall 60A', 'Claas Arion 650', 'Claas Arion 410', 'Claas Arion 440', 'Claas 2500', 'Claas Arion 440', 'Case STX380', 'AGCO Allis 4650', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 630', 'AGCO Allis 5650', 'Claas Arion 620', 'Claas Arion 660', 'Claas Arion 460', 'JCB Fastrac 4220', 'Claas Arion 620', 'Claas Arion 520', 'Claas Arion 660', 'Case Farmall 35B', 'Claas Arion 610', 'Claas Axion 830', 'Claas Arion 650', 'Claas 3000', 'JCB Fastrac 4220', 'Claas Arion 610', 'Claas Elios 220', 'Claas Arion 620', 'Claas Nexos 240 VL', 'Claas Axion 830', 'Claas Arion 650', 'Claas Arion 630', 'Pasquali EOS 5.50AR', 'Claas Arion 430', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 630', 'Claas Arion 430', 'Claas Arion 610', 'Claas Arion 410', 'Claas Axos 320', 'AGCO Allis 4660', 'Claas Arion 460', 'Case Maxxum 125', 'Claas Arion 620', 'Fendt Favorit 620LS', 'Claas Arion 530', 'AGCO Allis 8610', 'Claas Arion 450', 'JCB Fastrac 4220', 'Claas Arion 610', 'Massey Ferguson 7619', 'Claas Nexos 230', 'John Deere 2630', 'Claas Arion 460', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 650', 'Claas Nexos 240 VL', 'Claas Arion 620', 'Claas Arion 660', 'New Holland T7030', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 610', 'Claas Arion 450', 'Claas Axion 830', 'Claas 2500', 'Claas 556', 'Claas Arion 620', 'Claas Axos 310', 'Fendt 1038 Vario', 'Case Farmall 30B', 'Case CVX 150', 'AGCO Allis 4660', 'Claas Axion 920', 'Claas Axion 870', 'JCB Fastrac 4220', 'Claas Arion 460', 'Claas Arion 650', 'AGCO Allis 5680', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 620', 'Fendt Favorit 620LS', 'Claas Xerion 4200', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 510', 'Claas Axos 340', 'Case Puma 165', 'Claas Arion 460', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 630', 'Claas Arion 620', 'Claas Arion 650', 'Claas Arion 630', 'Claas Arion 430', 'Claas Arion 410', 'Claas 3000', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Ares 697', 'John Deere 6520', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 460', 'Claas Arion 460', 'Claas Axion 810', 'JCB 3330', 'Claas Arion 630', 'Claas Axion 820', 'Claas Arion 440', 'Claas Arion 530', 'Claas Xerion 3300', 'Claas Arion 650', 'Claas 556', 'Claas Arion 610', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 410', 'Claas Arion 620', 'JCB 3330', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 530', 'Case MXM155', 'Claas Arion 430', 'Claas Arion 630', 'JCB 3330', 'Claas Arion 440', 'Claas 2500', 'Claas 2500', 'Claas Arion 410', 'Claas Arion 460', 'New Holland T1010', 'Claas Arion 620', 'Claas 3000', 'Claas 2500', 'Claas Arion 620', 'AGCO RT140A', 'Claas Axos 340', 'Claas Arion 620', 'Claas Arion 620', 'New Holland T7.250', 'Claas Axos 340', 'Claas Arion 650', 'AGCO Allis 4660', 'AGCO Allis 4660', 'Claas Arion 620', 'JCB Fastrac 4220', 'Claas Arion 620', 'Claas 2500', 'AGCO Allis 5650', 'Case Farmall 60A', 'AGCO RT140A', 'AGCO Allis 8610', 'Claas Axos 340', 'Case MXU100', 'AGCO Allis 8610', 'AGCO Allis 4660', 'Claas Talos 130', 'Claas Axion 850', 'Claas Arion 460', 'Claas Arion 620', 'AGCO Allis 7630', 'Claas 3000', 'Claas Arion 510', 'AGCO Allis 4650', 'Claas Nexos 240 F', 'Claas Axos 340', 'Claas Arion 650', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 610', 'Fendt 927', 'JCB 3330', 'JCB Fastrac 4220', 'Claas Arion 530', 'Claas Arion 620', 'AGCO Allis 5680', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 460', 'AGCO Allis 8630', 'Claas Arion 620', 'Claas Arion 450', 'McCormick MTX120', 'Claas Arion 430', 'Claas Arion 430', 'Claas Talos 240', 'Claas Arion 410', 'Claas Elios 230', 'Massey Ferguson 5460', 'Claas Arion 460', 'John Deere 2640', 'Claas Elios 220', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 630', 'Claas 3000', 'AGCO RT140A', 'Claas Arion 660', 'Massey Ferguson 5440', 'Claas 2500', 'Case Optum 270', 'Claas Talos 240', 'Claas Arion 620', 'New Holland TL80', 'Case CX80', 'Claas Arion 460', 'Massey Ferguson 4445', 'JCB Fastrac 1115', 'JCB 3330', 'New Holland PowerStar 90', 'Case Maxxum 115', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axos 320', 'Claas Arion 620', 'Claas Arion 660', 'Claas Arion 620', 'Claas 3000', 'Fendt Favorit 610SL', 'Claas Arion 620', 'Claas Arion 630', 'Claas 65E', 'Claas Talos 220', 'Claas 616', 'Landini 6-120C', 'Claas 2500', 'Claas Arion 620', 'Deutz Fahr K420', 'Claas Arion 420', 'John Deere 2640', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'JCB Fastrac 4220', 'Claas Arion 610', 'Claas Nexos 240 VL', 'Claas 2500', 'Claas Axos 340', 'New Holland TN95F', 'Claas 75E', 'Claas 3000', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 450', 'Claas 3000', 'Claas Arion 620', 'Claas Arion 630', 'AGCO Allis 7630', 'Claas Arion 630', 'Claas Axion 820', 'Claas Arion 450', 'New Holland TS6030', 'Claas Arion 430', 'Claas Arion 630', 'Claas 3000', 'Claas Arion 430', 'Claas Arion 610', 'Claas Arion 430', 'Case Steiger 620', 'Claas Arion 620', 'Massey Ferguson 6270', 'Claas Nexos 230', 'Claas Arion 430', 'Claas Arion 620', 'AGCO Allis 4660', 'K

In [55]:
df['new_combined_Jaccard'] = new_combined_Jaccard_list
df['new_Jaccard_mapped_HP'] = (df['new_combined_Jaccard']).map(dictionary)

In [56]:
df

,ReportingPeriod,SourceInstanceCd,ConsolidationCd,BusinessUnitDesc,AgreementNbr,AgreementClassificationRefCd,AgreementStatusRefCd,Agreement_Exposure_EUR,Agreement_NetPrincipalBalanceAmt_EUR,FinanceAgreementLineNbr,...,new_ModelDescr,new_CombinedColumn,new_mapped_HP,new_Jaccard_mapped_HP,new_combined_Levenshtein,new_Levenshtein_mapped_HP,new_combined_cosine,new_cosine_mapped_HP,CombinedColumn,new_combined_Jaccard
0,M202110,INFAU,AGAAU,Food & Agriculture,016-0034538-004,BLO,BOOKED,32180.796374,32180.796374,016-0034538-004_488868,...,7250 TTV,Deutz Fahr 7250 TTV,236,236,Deutz Fahr 7250 TTV,236,Deutz Fahr 4.85,82,Deutz Fahr 7250TTV,Deutz Fahr 7250 TTV
1,M202110,INFAU,AGAAU,Food & Agriculture,016-0038548-001,BLO,BOOKED,109052.852056,109052.852056,016-0038548-001_529392,...,N 180a,Claas N 180a,NaN,114,Claas Axion 810,200,Claas Axion 810,200,Claas AXION 810,AGCO Allis 8610
2,M202110,INFAU,AGAAU,Food & Agriculture,016-0044635-001,BLO,BOOKED,28089.070897,28089.070897,016-0044635-001_477195,...,MTX110,McCormick MTX110,116,116,McCormick MTX110,116,McCormick C100,102,McCormick TMAX100PS,McCormick MTX110
3,M202110,INFAU,AGAAU,Food & Agriculture,016-0054437-001,BLO,BOOKED,24748.760117,24748.760117,016-0054437-001_501417,...,6160 TTV,Deutz Fahr 6160 TTV,155,155,Deutz Fahr TTV 610,157,Deutz Fahr 4.85,82,Deutz Fahr TTV610,Deutz Fahr 6160 TTV
4,M202110,INFAU,AGAAU,Food & Agriculture,016-0061278-003,BLO,BOOKED,20454.509550,20371.246358,016-0061278-003_314895,...,1255 XL,Case 1255 XL,125,125,Case MXU115 Value,116,Case Maxxum 125,125,Case MAXXUM 125 & LOADER,Case MXU125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4866,M202110,INFAU,AGANZ,Food & Agriculture,282-0454379-001,BLO,BOOKED,42681.457769,42681.457769,282-0454379-001_482101,...,7R 210,John Deere 7R 210,210,210,John Deere 6130R,130,John Deere 6130R,130,John Deere 6130R (2017),John Deere 7R 210
4867,M202110,INFAU,AGANZ,Food & Agriculture,282-0458168-001,BLO,BOOKED,37816.362965,37816.362965,282-0458168-001_512843,...,6130R,John Deere 6130R,130,130,John Deere 6130R,130,John Deere 6130R,130,John Deere 6130R,John Deere 6130R
4868,M202110,INFAU,AGANZ,Food & Agriculture,282-0498175-001,BLO,BOOKED,150660.428466,150660.428466,282-0498175-001_510073,...,6215 RC,John Deere 6215 RC,NaN,23,John Deere 6215R,215,John Deere 6215R,215,John Deere 6215R (2020),John Deere 1025R
4869,M202110,INFAU,AGANZ,Food & Agriculture,282-0514496-001,BLO,BOOKED,95017.877370,95017.877370,282-0514496-001_530507,...,6215 RC,John Deere 6215 RC,NaN,23,John Deere 6155R,155,John Deere 6155R,155,John Deere 6155R (2019),John Deere 1025R
4870,M202110,INFAU,AGANZ,Food & Agriculture,282-0527441-001,BLO,BOOKED,35372.722236,35372.722236,282-0527441-001_526297,...,1026R,John Deere 1026R,25,25,John Deere 6210R,210,John Deere 6210R,210,John Deere 6210R,John Deere 1026R

In [57]:
string_list = data_combined_list
new_combined_Levenshtein_list = []

for i in range(len(df_combined_list)):
    if isinstance(df_combined_list[i], str):
        target_string = df_combined_list[i]
        most_similar, distance = find_most_similar_string_Levenshtein(target_string, string_list)
        new_combined_Levenshtein_list.append(most_similar)
    else:
        new_combined_Levenshtein_list.append(None)  # Handle non-string values

print(new_combined_Levenshtein_list)

['Deutz Fahr 7250 TTV', 'Claas Axion 810', 'McCormick MTX110', 'Deutz Fahr TTV 610', 'Case MXU115 Value', 'John Deere 4760', 'Case MX200', 'Case Puma 165', 'Valtra T191', 'Claas 65E', 'Case STX325', 'Case MXU115 Value', 'Deutz Fahr Agroplus 410', 'Case STX325', 'Case STX375', 'New Holland L85', 'Kubota M7040', 'Valtra 3500', 'Case JX75', 'New Holland T4.75', 'Deutz Fahr Agroplus F430', 'Deutz Fahr Agroplus F430', 'New Holland T9040', 'Massey Ferguson 455 Xtra', 'Massey Ferguson 7475', 'Massey Ferguson 6445', 'Case Steiger 485', 'John Deere 8220T', 'Kubota M7950HC', 'Antonio Carraro TRH 9800', 'Valtra 6400', 'John Deere 9520T', 'John Deere 6430', 'John Deere 6120E', 'John Deere 8320', 'Valtra M120', 'John Deere 6125R', 'Case 9330', 'John Deere 3045R', 'Claas Axos 320', 'John Deere 20A', 'Carraro 4500C', 'Fendt 828', 'Massey Ferguson 6614', 'New Holland T8030', 'John Deere 8345R', 'John Deere 7210R', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.435', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.435', 'New Holland T8.320', 'Case Maxxum 125', 'JCB 3330', 'Fendt 930', 'Kubota M4030SU', 'Kubota M4030SU', 'John Deere 6140M', 'Claas 456', 'Case MXU115 Value', 'John Deere 5083E', 'Case MX240', 'Case MXU130 Value', 'Valtra 6400', 'Case Magnum 260', 'Case Farmall 30B', 'Case STX450', 'John Deere 9570R', 'John Deere 9630', 'JCB 3330', 'New Holland T8.360', 'Case JXU 115', 'TYM T700', 'Valtra N101', 'Case MXM120', 'John Deere 6140R', 'Case Maxxum 110', 'John Deere 7930', 'Mahindra 6110', 'Farmtrac FT 30', 'McCormick MTX185', 'Case MX90C', 'Antonio Carraro Mach 2', 'John Deere 8120T', 'Zetor 5245', 'Valtra 3500', 'McCormick CX110', 'Claas Arion 530', 'New Holland T8.390', 'Case MX275', 'Case 300', 'Case Farmall 30B', 'Case Farmall 30B', 'John Deere 9460R', 'Mahindra 4025', 'Apollo 954', 'McCormick C95 Max', 'Case MXU125', 'Case Steiger 435QT', 'Kubota L3800', 'New Holland TC21DA', 'Case 300', 'Apollo 354', 'New Holland T7.210', 'Farmtrac 300DTC', 'New Holland TL100A', 'Apollo 854', 'Apollo 554', 'Massey Ferguson 6130', 'Solis 45', 'Apollo 254', 'Apollo 454', 'Apollo 354', 'John Deere 6910', 'Landini Rex 95', 'John Deere 5325', 'Farmtrac 320DTC', 'Apollo 454', 'John Deere 8530', 'Kubota M108 DC', 'Kubota M108 DC', 'Kubota M108 DC', 'Kubota M108 DC', 'Kubota M108 DC', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Kubota M108', 'Apollo 454', 'Apollo 454', 'Apollo 454', 'Fendt 1038 Vario', 'New Holland T7050', 'New Holland TS100A', 'McCormick MTX135', 'Apollo 554', 'Apollo 354', 'Farmtrac 320DTC', 'Farmtrac FT 30', 'Case Farmall 110N', 'Solis 110', 'Apollo 454', 'Massey Ferguson 5435', 'Massey Ferguson 4270', 'Apollo 454', 'Apollo 854', 'Claas 2500', 'Fendt 412', 'Fendt 305 LS', 'New Holland T7.185', 'Apollo 954', 'Kubota M108 DC', 'Kubota M110GX', 'Kubota M135GX', 'Kubota M108 DC', 'Kubota M110GX', 'Kubota M110GX', 'Kubota M108 DC', 'Kubota M110GX', 'Kubota M135', 'Kubota M135', 'Deutz Fahr 6215 RC', 'Deutz Fahr 6215 RC', 'Apollo 954', 'Apollo 454', 'Apollo 554', 'Case 500', 'Farmtrac 360DTC', 'New Holland T7.185', 'Farmtrac 270DTC', 'Apollo 354', 'Kubota M108 DC', 'Kubota M108 DC', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Apollo 454', 'Massey Ferguson 5445', 'John Deere 6195R', 'John Deere 75C', 'McCormick MTX135', 'John Deere 8310R', 'McCormick MC90', 'Deutz Fahr 4050E Keyline', 'New Holland T4.55', 'Apollo 454', 'Fendt 716', 'McCormick CX85', 'Fendt 936', 'John Deere 9560RT', 'John Deere 6145R', 'Apollo 454', 'Apollo 254', 'Apollo 354', 'Apollo 354', 'Apollo 454', 'Apollo 554', 'Apollo 554', 'John Deere 6430', 'Case Steiger 600', 'Apollo 554', 'John Deere 6125M', 'John Deere 6105R', 'Apollo 554', 'Valtra N121', 'Case JX70', 'Apollo 554', 'Apollo 354', 'Landini  8865 super', 'Apollo 454', 'Apollo 454', 'Antonio Carraro TRX 7800S', 'Apollo 454', 'McCormick MC90', 'Apollo 354', 'Apollo 554', 'Case STX275', 'Claas Arion 430', 'Apollo 354', 'Apollo 554', 'Case Steiger 600', 'John Deere 8360RT', 'John Deere 8360R', 'Kubota M7.171', 'Apollo 554', 'Apollo 554', 'Case Maxxum 120', 'Apollo 954', 'New Holland T5.95', 'Apollo 454', 'New Holland T7040', 'John Deere 6420', 'Apollo 354', 'Apollo 354', 'Landini Rex 75', 'Apollo 454', 'Landini Powerfarm 75', 'Apollo 954', 'Landini 8860', 'Apollo 554', 'Apollo 554', 'Apollo 554', 'Claas Axion 840', 'Apollo 354', 'John Deere 8245R', 'Apollo 354', 'John Deere 7210R', 'John Deere 6125R', 'John Deere 4720', 'Case Magnum 340', 'New Holland TS110A', 'John Deere 8310', 'John Deere 20A', 'John Deere 6155M', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'John Deere 6125M', 'Apollo 554', 'Apollo 254', 'Apollo 554', 'Apollo 554', 'McCormick X5.40', 'Apollo 454', 'Apollo 554', 'Apollo 554', 'Apollo 354', 'Kubota M7950HC', 'Carraro 734', 'Carraro 420.5', 'Claas 95E', 'Claas 95E', 'Apollo 354', 'John Deere 8300', 'Kubota M7950HC', 'Apollo 554', 'Apollo 454', 'Apollo 554', 'Landini 75', 'Valtra N114', 'Landini 8860', 'Apollo 554', 'Apollo 1104', 'Apollo 454', 'Apollo 554', 'John Deere 7930', 'Landini 75', 'Landini 10000S', 'Apollo 454', 'Apollo 454', 'Apollo 454', 'John Deere 6130R', 'Landini 4-105', 'New Holland T7.170', 'Mahindra 6000', 'Mahindra 3550', 'Case CVX 120', 'Apollo 454', 'Apollo 554', 'John Deere 3300', 'New Holland TM130', 'Daedong  DK65', 'Case Puma 150 X', 'Apollo 554', 'John Deere 8130', 'Landini Powerfarm 90', 'Landini  8865 super', 'Landini 4-105', 'Landini  8865', 'Landini Technofarm 85', 'Landini  8865', 'Landini 7860', 'Landini Mistral 45', 'Landini  8865', 'Landini 8860', 'Landini 120', 'Landini Rex 100', 'Landini 8860', 'Landini Rex 80', 'Landini 8860', 'Landini  8865', 'Landini 4-105', 'Landini Rex 120', 'Kubota GL-530', 'Case 300', 'Landini Rex 95', 'Landini 4-105', 'Landini 7860', 'Landini Rex 90', 'Landini 7860', 'Landini Powerfarm 110', 'Landini  8865 super', 'Landini 6-130C', 'Landini Powerfarm 75', 'Landini  8865 super', 'Claas Xerion 5000', 'Claas Arion 620', 'Claas Arion 410', 'Claas Axion 950', 'Claas Axion 870', 'Claas Arion 620', 'Claas 2500', 'Claas Axion 950', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 410', 'Claas Arion 430', 'Claas Arion 630', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 530', 'Claas Arion 620', 'Claas 436', 'Claas Arion 530', 'Claas Arion 530', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 510', 'Claas Arion 630', 'Claas Arion 640', 'Claas Axos 320', 'Claas Arion 610', 'Claas Arion 610', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 510', 'Claas Axion 930', 'Claas Arion 630', 'Claas Arion 430', 'Claas Arion 410', 'Claas Arion 650', 'Claas Arion 630', 'Claas Arion 620', 'Claas Arion 440', 'Claas Arion 620', 'Claas Arion 650', 'Claas Arion 440', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 840', 'Claas Arion 430', 'Claas Arion 620', 'Claas Axion 840', 'Claas Axos 340', 'Claas 2500', 'Claas Arion 640', 'Claas Arion 640', 'Claas Axion 830', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 870', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 620', 'Claas Axion 930', 'Claas Arion 610', 'Claas Axion 850', 'Claas Axion 950', 'Claas 2500', 'Claas Arion 410', 'Claas Arion 640', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 530', 'Claas Arion 630', 'Claas Arion 530', 'Claas Arion 660', 'Claas Arion 650', 'Claas Axion 830', 'Claas Arion 620', 'Claas Axion 870', 'Claas Arion 650', 'Claas Arion 640', 'Claas Arion 410', 'Mahindra 4025', 'Claas Arion 630', 'Claas Axion 800', 'Claas Arion 650', 'Claas Arion 640', 'Claas Arion 530', 'Claas 2500', 'Claas Arion 610', 'Claas Arion 610', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 520', 'Claas Arion 620', 'Claas Axion 800', 'Claas Arion 620', 'Claas 2500', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 430', 'Claas Axion 930', 'Claas Axion 800', 'Claas 546', 'Claas Axion 950', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 430', 'Claas 65E', 'Claas Axos 340', 'Claas Arion 610', 'Claas Arion 530', 'Claas 3300 Trac', 'Claas Arion 630', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 810', 'Claas Nexos 240 VL', 'Claas Axion 830', 'Claas Arion 630', 'Claas Arion 610', 'Claas Arion 430', 'Deutz Fahr Agrotron 90', 'Claas Arion 530', 'Claas Arion 520', 'Claas Arion 620', 'Claas Arion 610', 'Claas 3000', 'Claas 2500', 'Claas Axion 930', 'Claas Arion 640', 'Claas Axion 870', 'Claas Axion 810', 'Claas Axion 870', 'Claas Axion 870', 'Mahindra mForce 100', 'Claas Arion 650', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 530', 'Claas Arion 430', 'Claas Arion 620', 'Claas Axos 330', 'Claas Arion 610', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 430', 'Claas Arion 620', 'Claas Axion 800', 'Claas Arion 650', 'Claas Arion 430', 'Claas Axos 330', 'Claas Arion 640', 'Claas 2500', 'Claas Axion 830', 'Claas Arion 630', 'Claas 3000', 'Claas 3000', 'John Deere 6140M', 'John Deere 5065M', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 830', 'Claas Arion 410', 'Claas Arion 410', 'Claas Arion 610', 'Claas Nexos 240 VL', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 440', 'Claas Arion 430', 'Claas Arion 630', 'Claas 2500', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 610', 'Claas Axion 930', 'Claas Arion 620', 'Claas Arion 430', 'Claas Arion 640', 'Claas Arion 410', 'New Holland T7.235', 'Claas Axos 320', 'Claas Arion 630', 'Claas 2500', 'Claas Axos 340', 'Claas Arion 610', 'Claas Axion 930', 'Claas Axion 830', 'Valtra 6400', 'Claas Axion 830', 'Claas Arion 530', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 620', 'New Holland TL70A', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 620', 'Claas Axos 330', 'Claas Arion 420', 'New Holland TS100A', 'Claas 3000', 'Claas Arion 610', 'Claas Axion 840', 'Claas Arion 620', 'Claas Arion 430', 'Claas Axion 850', 'Claas Arion 620', 'Claas Arion 430', 'Claas Arion 620', 'Claas 3300 Trac', 'Claas Axos 330', 'Claas Axion 930', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 530', 'Claas Arion 430', 'Claas Axion 930', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 800', 'Claas 2500', 'Claas Arion 430', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 810', 'Claas Axion 930', 'Claas Arion 620', 'Claas Arion 610', 'Deutz Fahr TTV 620', 'Claas Axion 830', 'Claas Arion 430', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 430', 'Claas Axion 930', 'Claas Arion 640', 'Claas Axion 830', 'Claas Arion 630', 'Claas Arion 420', 'Claas Arion 650', 'Claas 2500', 'Case Puma 125', 'Claas Arion 430', 'Claas Arion 640', 'Claas Arion 430', 'Claas Axos 330', 'Claas Arion 620', 'Claas Arion 410', 'Claas Arion 640', 'Claas Axos 330', 'Claas Arion 620', 'Claas Arion 620', 'New Holland TD95D', 'Claas Axion 930', 'Claas Arion 430', 'Claas Arion 620', 'Claas 826', 'Case MXU135', 'Claas Axion 950', 'Claas 3300 Trac', 'Claas Arion 440', 'Claas Axion 930', 'Claas Arion 620', 'Claas Axos 320', 'Claas Arion 620', 'Claas Axos 320', 'Claas Arion 620', 'Deutz Fahr 5105', 'Claas Arion 410', 'Claas Arion 430', 'Fendt 712', 'Claas Axos 320', 'Claas Axion 830', 'Claas Axos 320', 'Claas Axos 320', 'Claas 2500', 'Claas Arion 610', 'Claas Arion 620', 'Claas Axion 930', 'Claas Axos 330', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 620', 'JCB Fastrac 8250', 'Claas Axion 870', 'Claas 2500', 'Claas Arion 620', 'Claas Axion 950', 'Claas Arion 610', 'Claas Arion 620', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 430', 'Claas Arion 650', 'Claas Arion 620', 'Claas Arion 460', 'Claas Arion 620', 'Claas Arion 620', 'Claas 2500', 'Claas Axion 870', 'Case Maxxum 110', 'Claas 616', 'Claas Arion 410', 'Claas Arion 410', 'Claas Arion 640', 'Claas Arion 620', 'Claas Axion 930', 'Massey Ferguson 435', 'Claas Axion 870', 'Case Farmall 95C', 'Claas Arion 640', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 410', 'Case 1130', 'Claas Arion 620', 'Yanmar AF330', 'Claas Axos 330', 'Claas Arion 610', 'Claas Arion 650', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 430', 'Claas Axos 330', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 410', 'Claas 2500', 'Claas Arion 610', 'Claas Arion 410', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 640', 'Claas 936', 'Claas Arion 440', 'Claas 2500', 'Claas Arion 430', 'Claas Arion 640', 'Claas Arion 620', 'Case Magnum 315', 'Claas Arion 430', 'Claas Axos 340', 'Claas 3000', 'Claas Arion 620', 'Claas Arion 440', 'Claas Arion 430', 'Claas Arion 610', 'Claas Arion 410', 'Claas Arion 410', 'Claas 2500', 'Claas 2500', 'Claas Arion 430', 'Claas Arion 640', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 620', 'Claas Arion 430', 'Claas Arion 430', 'Claas 2500', 'Claas 3000', 'Claas Arion 620', 'Claas 3000', 'Claas 2500', 'Claas 2500', 'Claas 85E', 'Claas Arion 640', 'Claas 2500', 'Claas 436', 'Claas Arion 640', 'Claas Arion 620', 'Claas 2500', 'Claas 2500', 'Claas 436', 'Claas 2500', 'Claas Arion 430', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 410', 'Claas Axion 950', 'Claas Axos 340', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 410', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 410', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 410', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 650', 'New Holland T6020 Elite', 'Case Magnum 180', 'Claas Nexos 220', 'Claas Nexos 220', 'Case PJ55', 'Claas Nexos 220', 'Claas Nexos 220', 'Claas Nexos 220', 'Claas Nexos 220', 'Claas Nexos 220', 'Claas Nexos 220', 'Claas Nexos 220', 'Claas Nexos 220', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'New Holland T5.105', 'Claas 2500', 'Claas Arion 630', 'Claas Arion 650', 'Claas Axion 800', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 620', 'Claas Axion 800', 'Claas 2500', 'JCB 3330', 'JCB Fastrac 4220', 'Claas Arion 650', 'Claas Axion 830', 'Claas Arion 630', 'Claas Arion 620', 'Claas Axos 340', 'Claas Arion 610', 'Claas Xerion 3800', 'Claas Arion 650', 'Claas Arion 620', 'Claas Arion 650', 'Claas Arion 410', 'Claas Arion 440', 'Claas 2500', 'Claas Arion 410', 'Claas Axion 830', 'Claas Arion 650', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 650', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 460', 'JCB Fastrac 4220', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 660', 'JCB Fastrac 135', 'Claas Arion 610', 'Claas Axion 830', 'Claas Arion 650', 'Claas 936', 'JCB Fastrac 4220', 'Claas Arion 610', 'Claas 3300 Trac', 'Claas Arion 620', 'Claas Nexos 240 VL', 'Claas Axion 830', 'Claas Arion 650', 'Claas 3300 Trac', 'Claas Xerion 5000', 'Claas Arion 430', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 630', 'Claas Arion 430', 'Claas Arion 610', 'Claas Arion 410', 'Claas Axos 330', 'Claas Arion 640', 'Claas Arion 640', 'Case Maxxum 125', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 610', 'Claas Arion 450', 'JCB 3330', 'Claas Arion 610', 'Massey Ferguson 7619', 'Claas Nexos 230', 'John Deere 6230', 'Claas Arion 640', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 650', 'Claas Nexos 240 VL', 'Claas Arion 620', 'Claas Arion 660', 'New Holland T7030', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 610', 'Claas Arion 450', 'Claas Axion 830', 'Claas Xerion 4500', 'Claas 65E', 'Claas Arion 620', 'Claas 3300 Trac', 'Landini Atlas 100', 'Case Farmall 31', 'Case CVX 150', 'Claas Arion 440', 'Claas Axion 920', 'Claas Axion 870', 'JCB Fastrac 4220', 'Claas Arion 640', 'Claas Arion 650', 'Claas Axion 850', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 430', 'Claas Arion 510', 'Claas Axos 340', 'Case Puma 165 X', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 630', 'Claas Arion 620', 'Claas Arion 650', 'Claas Arion 630', 'Claas Arion 430', 'Claas Arion 410', 'Claas 3000', 'Claas Arion 620', 'Claas Arion 620', 'Claas 3300 Trac', 'Claas Ares 697', 'John Deere 6520', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 640', 'Claas Arion 640', 'Claas Axion 810', 'JCB 3330', 'Claas Arion 630', 'Claas Axion 820', 'Claas Arion 410', 'Claas Arion 530', 'Claas Xerion 3300', 'Claas Arion 650', 'Claas 2500', 'Claas Arion 610', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 640', 'Claas Arion 620', 'JCB 3330', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 530', 'Case Farmall 115U', 'Claas Arion 430', 'Claas Arion 630', 'JCB 3330', 'Claas Arion 410', 'Claas 2500', 'Claas 2500', 'Claas Arion 410', 'Claas Arion 640', 'New Holland TB100', 'Claas Arion 620', 'Claas 3000', 'Claas 2500', 'Claas Arion 620', 'Claas Arion 410', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 620', 'New Holland T7.250', 'Claas Arion 430', 'Claas Arion 650', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 620', 'JCB Fastrac 4220', 'Claas Arion 620', 'Claas 2500', 'Claas Arion 650', 'Claas 3300 Trac', 'Claas Arion 410', 'Claas Arion 610', 'Claas Arion 430', 'Case MXU100', 'Claas Axion 810', 'Claas Arion 640', 'Claas Axos 310', 'Claas Axion 850', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 410', 'Claas Arion 510', 'Claas Arion 450', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 650', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 610', 'Fendt 927', 'JCB 3330', 'JCB Fastrac 4220', 'Claas Arion 530', 'Claas Arion 620', 'Claas Axion 850', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 640', 'Claas Axion 830', 'Claas Arion 620', 'Claas Arion 450', 'McCormick MTX120', 'Claas Arion 430', 'Claas Arion 430', 'Claas 426', 'Claas Arion 410', 'Claas Nexos 240 VL', 'Massey Ferguson 5460', 'Claas Arion 640', 'John Deere 6420', 'Claas Nexos 240 VL', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 630', 'Claas Axos 330', 'Claas Arion 410', 'Claas Arion 660', 'Massey Ferguson 5440', 'Claas 2500', 'Case Optum 270', 'Claas Arion 420', 'Claas 3300 Trac', 'New Holland TL80', 'Claas 2500', 'Claas Arion 640', 'Massey Ferguson 5445', 'JCB Fastrac 125', 'JCB 3330', 'New Holland T9.530 SmartTrax II', 'Case Maxxum 115', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axos 320', 'Claas Arion 620', 'Claas Arion 610', 'Claas Arion 620', 'Claas 3000', 'Claas Nexos 240 VL', 'Claas Arion 620', 'Claas Arion 630', 'Claas 65E', 'Claas Nexos 240 VL', 'Claas 616', 'Claas Arion 410', 'Claas 2500', 'Claas Arion 620', 'Deutz Fahr K420', 'Claas Arion 420', 'John Deere 6420', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'Claas Nexos 240 VL', 'JCB Fastrac 125', 'Claas Arion 610', 'Claas Nexos 240 VL', 'Claas 2500', 'Claas Axos 340', 'New Holland TN95F', 'Claas 217', 'Claas 436', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 450', 'Claas 3000', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 630', 'Claas Arion 630', 'Claas Axion 820', 'Claas Arion 450', 'New Holland TS6030', 'Claas Arion 430', 'Claas Arion 630', 'Claas 3000', 'Claas Arion 430', 'Claas Arion 610', 'Claas Arion 430', 'Claas 3300 Trac', 'Claas Arion 620', 'Massey Ferguson 6270', 'Claas Nexos 230', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 460', 'Kubota M8540', 'Claas Arion 640', 'Claas Axos 320', 'Claas Arion 420', 'Claas Ario

In [58]:
df['new_combined_Levenshtein'] = new_combined_Levenshtein_list
df['new_Levenshtein_mapped_HP'] = (df['new_combined_Levenshtein']).map(dictionary)

In [59]:
df

,ReportingPeriod,SourceInstanceCd,ConsolidationCd,BusinessUnitDesc,AgreementNbr,AgreementClassificationRefCd,AgreementStatusRefCd,Agreement_Exposure_EUR,Agreement_NetPrincipalBalanceAmt_EUR,FinanceAgreementLineNbr,...,new_ModelDescr,new_CombinedColumn,new_mapped_HP,new_Jaccard_mapped_HP,new_combined_Levenshtein,new_Levenshtein_mapped_HP,new_combined_cosine,new_cosine_mapped_HP,CombinedColumn,new_combined_Jaccard
0,M202110,INFAU,AGAAU,Food & Agriculture,016-0034538-004,BLO,BOOKED,32180.796374,32180.796374,016-0034538-004_488868,...,7250 TTV,Deutz Fahr 7250 TTV,236,236,Deutz Fahr 7250 TTV,236,Deutz Fahr 4.85,82,Deutz Fahr 7250TTV,Deutz Fahr 7250 TTV
1,M202110,INFAU,AGAAU,Food & Agriculture,016-0038548-001,BLO,BOOKED,109052.852056,109052.852056,016-0038548-001_529392,...,N 180a,Claas N 180a,NaN,114,Claas Axion 810,200,Claas Axion 810,200,Claas AXION 810,AGCO Allis 8610
2,M202110,INFAU,AGAAU,Food & Agriculture,016-0044635-001,BLO,BOOKED,28089.070897,28089.070897,016-0044635-001_477195,...,MTX110,McCormick MTX110,116,116,McCormick MTX110,116,McCormick C100,102,McCormick TMAX100PS,McCormick MTX110
3,M202110,INFAU,AGAAU,Food & Agriculture,016-0054437-001,BLO,BOOKED,24748.760117,24748.760117,016-0054437-001_501417,...,6160 TTV,Deutz Fahr 6160 TTV,155,155,Deutz Fahr TTV 610,157,Deutz Fahr 4.85,82,Deutz Fahr TTV610,Deutz Fahr 6160 TTV
4,M202110,INFAU,AGAAU,Food & Agriculture,016-0061278-003,BLO,BOOKED,20454.509550,20371.246358,016-0061278-003_314895,...,1255 XL,Case 1255 XL,125,125,Case MXU115 Value,116,Case Maxxum 125,125,Case MAXXUM 125 & LOADER,Case MXU125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4866,M202110,INFAU,AGANZ,Food & Agriculture,282-0454379-001,BLO,BOOKED,42681.457769,42681.457769,282-0454379-001_482101,...,7R 210,John Deere 7R 210,210,210,John Deere 6130R,130,John Deere 6130R,130,John Deere 6130R (2017),John Deere 7R 210
4867,M202110,INFAU,AGANZ,Food & Agriculture,282-0458168-001,BLO,BOOKED,37816.362965,37816.362965,282-0458168-001_512843,...,6130R,John Deere 6130R,130,130,John Deere 6130R,130,John Deere 6130R,130,John Deere 6130R,John Deere 6130R
4868,M202110,INFAU,AGANZ,Food & Agriculture,282-0498175-001,BLO,BOOKED,150660.428466,150660.428466,282-0498175-001_510073,...,6215 RC,John Deere 6215 RC,NaN,23,John Deere 6215R,215,John Deere 6215R,215,John Deere 6215R (2020),John Deere 1025R
4869,M202110,INFAU,AGANZ,Food & Agriculture,282-0514496-001,BLO,BOOKED,95017.877370,95017.877370,282-0514496-001_530507,...,6215 RC,John Deere 6215 RC,NaN,23,John Deere 6155R,155,John Deere 6155R,155,John Deere 6155R (2019),John Deere 1025R
4870,M202110,INFAU,AGANZ,Food & Agriculture,282-0527441-001,BLO,BOOKED,35372.722236,35372.722236,282-0527441-001_526297,...,1026R,John Deere 1026R,25,25,John Deere 6210R,210,John Deere 6210R,210,John Deere 6210R,John Deere 1026R

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def find_most_similar_string_cosine(target, string_list):
    # Combine the target string and string list to create a collection of texts
    text_collection = [target] + string_list
    
    # Create a TF-IDF vectorizer
    vectorizer = TfidfVectorizer()
    
    # Convert the text collection to TF-IDF vectors
    tfidf_matrix = vectorizer.fit_transform(text_collection)
    
    # Calculate cosine similarity matrix
    cosine_similarities = cosine_similarity(tfidf_matrix[0], tfidf_matrix[1:])[0]
    
    # Find the index of the most similar string
    most_similar_index = cosine_similarities.argmax()
    most_similar_string = string_list[most_similar_index]
    max_similarity = cosine_similarities[most_similar_index]
    
    return most_similar_string, max_similarity

In [61]:
string_list = data_combined_list
new_combined_cosine_list = []

for i in range(len(df_combined_list)):
    if isinstance(df_combined_list[i], str):
        target_string = df_combined_list[i]
        most_similar, distance = find_most_similar_string_cosine(target_string, string_list)
        new_combined_cosine_list.append(most_similar)
    else:
        new_combined_cosine_list.append(None)  # Handle non-string values

print(new_combined_cosine_list)

['Deutz Fahr 4.85', 'Claas Axion 810', 'McCormick C100', 'Deutz Fahr 4.85', 'Case Maxxum 125', 'John Deere 4760', 'Case Magnum 200', 'Case Puma 165 X', 'Valtra T191', 'Claas Ares 657', 'AGCO DT180A', 'Case 310-B', 'Deutz Fahr Agroplus 420', 'AGCO DT180A', 'Case STX375', 'New Holland T6020', 'Kubota M7040', 'AGCO DT180A', 'Case 310-B', 'John Deere 75F', 'Deutz Fahr Agroplus F430', 'Deutz Fahr Agroplus F430', 'New Holland T9040', 'Massey Ferguson 5455', 'Massey Ferguson 7475', 'Massey Ferguson 6445', 'Case Steiger 485', 'John Deere Q-85', 'Kubota A-175', 'Antonio Carraro Mach 2', 'Valtra 6400', 'John Deere 9520T', 'John Deere 6430', 'John Deere 6120R', 'John Deere 8320', 'Valtra M120', 'John Deere 6125R', 'Case 9330', 'John Deere 3045R', 'Claas Axos 310', 'John Deere Q-85', 'AGCO DT180A', 'Fendt 828', 'Massey Ferguson 85', 'New Holland T8030', 'John Deere 8345R', 'John Deere 7210R', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.435', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.320', 'New Holland T8.435', 'New Holland T8.320', 'Case Maxxum 125', 'JCB Fastrac 145', 'Fendt 930', 'Kubota A-175', 'Kubota A-175', 'John Deere 6140M', 'Claas 456', 'Case Maxxum 125', 'John Deere 5083E', 'Case MX240', 'Case Magnum 380', 'Valtra 6400', 'Case Magnum 260', 'Case Farmall 95', 'Case Steiger 450', 'John Deere 9570R', 'John Deere 9630', 'JCB Fastrac 8330', 'New Holland T8.360', 'Case Maxxum 115', 'TYM T700', 'Valtra 3300', 'Case MXM120', 'John Deere 6140R', 'Case Maxxum 110', 'John Deere 7930', 'Mahindra 6110', 'Farmtrac 70', 'John Deere Q-85', 'Renault 90-32 MX', 'Antonio Carraro Mach 2', 'John Deere 8120', 'Zetor 5245', 'AGCO DT180A', 'McCormick CX110', 'Claas Arion 530', 'New Holland T8.390', 'AGCO DT180A', 'AGCO DT180A', 'Case Farmall 95', 'Case Farmall 95', 'John Deere 9460R', 'Mahindra 4025', 'Apollo 954', 'Landini 95', 'Case Maxxum 125', 'AGCO DT180A', 'Kubota L3800', 'New Holland T6020', 'Case 310-B', 'Apollo 254', 'New Holland T7.210', 'Farmtrac 70', 'New Holland TL100A', 'Apollo 854', 'Apollo 554', 'Massey Ferguson 6130', 'Apollo 354', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'John Deere 6910', 'Landini 95', 'John Deere 5325', 'Farmtrac 70', 'Apollo 254', 'John Deere Q-85', 'Kubota A-175', 'Kubota A-175', 'Kubota A-175', 'Kubota A-175', 'Kubota A-175', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Kubota M108', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'AGCO DT180A', 'New Holland T7050', 'New Holland TS100A', 'McCormick MTX135', 'Apollo 554', 'Apollo 254', 'Farmtrac 70', 'Kubota FT30', 'Case Farmall 110N', 'AGCO DT180A', 'Apollo 454', 'Massey Ferguson 5435', 'Massey Ferguson 4270', 'Apollo 454', 'Apollo 254', 'Claas 35', 'Fendt 412', 'Fendt 305 LS', 'New Holland T7.185', 'Apollo 254', 'Kubota A-175', 'Kubota M110GX', 'Kubota M135GX', 'Kubota A-175', 'Kubota M110GX', 'Kubota M110GX', 'Kubota A-175', 'Kubota M110GX', 'Kubota M135', 'Kubota M135', 'Deutz Fahr 4.85', 'Deutz Fahr 4.85', 'Apollo 954', 'Apollo 254', 'Apollo 554', 'Case Farmall 50B', 'Farmtrac 70', 'New Holland T7.185', 'Farmtrac 70', 'Apollo 254', 'Kubota A-175', 'Kubota A-175', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Fendt 211P', 'Apollo 254', 'Massey Ferguson 5445', 'John Deere 6195R', 'Landini 75', 'McCormick MTX135', 'John Deere 8310R', 'McCormick MC90', 'Deutz Fahr Agrotron 165.7', 'New Holland T4.55', 'Apollo 254', 'Fendt 716', 'John Deere Q-85', 'Fendt 936', 'John Deere 9560R', 'John Deere 6145R', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'John Deere 6430', 'Case Steiger 350', 'Apollo 254', 'John Deere 6125M', 'John Deere Q-85', 'Apollo 554', 'Valtra 3300', 'Case JX70', 'Apollo 254', 'Apollo 254', 'Landini 8860', 'Apollo 254', 'Apollo 454', 'Antonio Carraro TTR 7800', 'Apollo 254', 'McCormick MC90', 'Apollo 254', 'Apollo 254', 'Case Steiger 350', 'Claas Arion 430', 'Apollo 254', 'Apollo 554', 'Case Steiger 350', 'John Deere 8360RT', 'John Deere 8360R', 'Kubota A-175', 'Apollo 254', 'Apollo 254', 'Case Maxxum 120', 'Apollo 254', 'New Holland T5.95', 'Apollo 254', 'New Holland T7040', 'John Deere 6420', 'Apollo 254', 'Apollo 254', 'Landini 75', 'Apollo 254', 'Landini 75', 'Apollo 254', 'Landini 8860', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'Claas Axion 840', 'Apollo 254', 'John Deere 8245R', 'Apollo 254', 'John Deere 7210R', 'John Deere 6125R', 'John Deere Q-85', 'Case Magnum 340', 'New Holland TS110', 'John Deere 8310', 'John Deere Q-85', 'John Deere 6155M', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'JCB 3330', 'John Deere 6125M', 'Apollo 554', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'McCormick X5.40', 'Apollo 254', 'Apollo 254', 'Apollo 554', 'Apollo 254', 'Kubota A-175', 'Antonio Carraro TRX 9800', 'Carraro 420.5', 'Claas 35', 'Claas 35', 'Apollo 254', 'John Deere 8300', 'Kubota A-175', 'Apollo 554', 'Apollo 254', 'Apollo 554', 'Landini 75', 'Valtra 3300', 'Landini 75', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'John Deere 7930', 'Landini 75', 'Landini 75', 'Apollo 254', 'Apollo 254', 'Apollo 254', 'John Deere 6130R', 'Landini 75', 'New Holland T7.170', 'Landini 6060', 'John Deere 3650', 'Case 310-B', 'Apollo 254', 'Apollo 254', 'John Deere Q-85', 'New Holland TM130', 'AGCO DT180A', 'Case Puma 155', 'Apollo 254', 'John Deere 8130', 'Landini Powerfarm 90', 'Landini  8865', 'Landini 4-105', 'Landini  8865 super', 'Landini Technofarm 85', 'Landini  8865 super', 'Landini 75', 'Landini 75', 'Landini 75', 'Landini  8865', 'Landini 75', 'Landini 75', 'Landini  8865', 'Landini Rex 80', 'Landini  8865', 'Landini  8865 super', 'Landini 4-105', 'Landini Rex 120', 'Kubota A-175', 'AGCO DT180A', 'Landini Rex 75', 'Landini 4-105', 'Landini 75', 'John Deere 90F', 'Landini 75', 'Landini 75', 'Landini  8865', 'Landini 75', 'Landini 75', 'Landini  8865', 'Claas Xerion 5000', 'Claas Arion 420', 'Claas Arion 410', 'Claas Axion 950', 'Claas Axion 870', 'Claas Arion 620', 'Claas 35', 'Claas Axion 950', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 530', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 530', 'Claas Arion 530', 'Claas Arion 640', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 650', 'Claas Arion 630', 'Claas Arion 420', 'Claas Axos 320', 'Claas Arion 420', 'Claas Arion 610', 'Claas Arion 620', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 650', 'Claas Axion 930', 'Claas 35', 'Claas Arion 430', 'Claas Arion 410', 'Claas Arion 650', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 440', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 440', 'Claas Arion 420', 'Claas Arion 620', 'Claas Axion 840', 'Claas Arion 430', 'Claas Arion 420', 'Claas Axion 840', 'Claas Axos 340', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axion 830', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 870', 'Claas Arion 460', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 620', 'Claas Axion 930', 'Claas Arion 610', 'Claas Axion 850', 'Claas Axion 950', 'Claas Arion 420', 'Claas Arion 410', 'Claas Arion 640', 'Claas Arion 620', 'Claas Axos 310', 'Claas Arion 530', 'Claas Arion 630', 'Claas Arion 530', 'Claas Arion 660', 'Claas Arion 650', 'Claas Axion 830', 'Claas Arion 420', 'Claas Axion 870', 'Claas Arion 650', 'Claas Arion 640', 'Claas Arion 410', 'Mahindra 350', 'Claas Arion 630', 'Claas Axion 830', 'Claas Arion 650', 'Claas Arion 640', 'Claas Arion 530', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 520', 'Claas Arion 620', 'Claas Axion 800', 'Claas Arion 420', 'Claas Arion 640', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axos 340', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 430', 'Claas Axion 930', 'Claas Axion 800', 'Claas Arion 540', 'Claas Axion 950', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas 35', 'Claas Axos 310', 'Claas Arion 610', 'Claas Arion 530', 'Claas Arion 640', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axion 810', 'Claas 35', 'Claas Axion 830', 'Claas Arion 630', 'Landini 6-120C', 'Claas Arion 430', 'Deutz Fahr Agrotron 90', 'Claas Arion 530', 'Claas Arion 520', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 620', 'Claas Axion 930', 'Claas Arion 640', 'Claas Axion 870', 'Claas Axion 810', 'Claas Axion 820', 'Claas Axion 820', 'Mahindra mForce 100', 'Claas Arion 650', 'Claas Arion 620', 'Claas 35', 'Claas Arion 530', 'Claas Arion 430', 'Claas Arion 420', 'Claas Axos 330', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axion 800', 'Claas Arion 650', 'Claas Arion 420', 'Claas Axos 330', 'Claas Arion 420', 'Claas Arion 620', 'Claas Axion 830', 'Claas Arion 630', 'Claas Arion 430', 'Claas 35', 'John Deere 6140M', 'John Deere 5065M', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 420', 'Claas Axos 340', 'Claas Arion 420', 'Claas Arion 620', 'Claas Axion 830', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 640', 'Claas Arion 620', 'Claas Arion 440', 'Claas Arion 430', 'Claas Arion 630', 'Claas Arion 620', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axion 930', 'Claas Arion 620', 'Claas Arion 430', 'Claas Arion 640', 'Claas Axos 310', 'New Holland T7.235', 'Claas Axos 310', 'Claas Arion 630', 'Claas 35', 'Claas Axos 340', 'Claas Arion 610', 'Claas Axion 930', 'Claas Axion 830', 'Claas Arion 640', 'Claas Axion 830', 'Claas Arion 530', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'New Holland TL70', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 620', 'Claas Axos 310', 'Claas Arion 420', 'New Holland TS100', 'Claas Arion 430', 'Claas Arion 420', 'Claas Axion 840', 'Claas Arion 620', 'Claas Arion 430', 'Claas Axion 850', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 620', 'Claas 35', 'Claas Axion 930', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 530', 'Claas Arion 420', 'Claas Axion 930', 'Claas Arion 620', 'Claas Arion 420', 'Claas Arion 620', 'Claas Axion 800', 'Claas Arion 620', 'Claas Arion 420', 'Claas 35', 'Claas Arion 620', 'Claas Arion 620', 'Claas Axion 810', 'Claas Axion 930', 'Claas Arion 620', 'Claas Arion 420', 'Deutz Fahr Agroplus 420', 'Claas Axion 830', 'Claas Arion 430', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 430', 'Claas Axion 930', 'Claas Arion 640', 'Claas Axion 830', 'Claas Arion 630', 'Claas Arion 420', 'Claas Arion 650', 'Claas 35', 'Case Puma 125', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axos 310', 'Claas Arion 620', 'Claas Arion 410', 'Claas Arion 420', 'Claas Axos 310', 'Claas Arion 620', 'Claas Arion 420', 'New Holland TD95D', 'Claas Axion 930', 'Claas Arion 430', 'Claas Arion 620', 'Claas 35', 'Case MXU135', 'Claas Axion 950', 'Claas 35', 'Claas Arion 440', 'Claas Axion 930', 'Claas Arion 620', 'Claas Axos 320', 'Claas Arion 420', 'Claas Axos 310', 'Claas Arion 620', 'Deutz Fahr 5105', 'Claas Arion 420', 'Claas Arion 430', 'Fendt 712', 'Claas Axos 320', 'Claas Axion 830', 'Claas Axos 320', 'Claas Axos 320', 'Claas Arion 640', 'Claas Arion 610', 'Claas Arion 620', 'Claas Axion 930', 'Claas Axos 330', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 420', 'Claas Axos 340', 'Claas Arion 620', 'JCB Fastrac 8250', 'Claas Axion 870', 'Claas 35', 'Claas Arion 420', 'Claas Axion 950', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 650', 'Claas Arion 620', 'Claas Arion 460', 'Claas Arion 420', 'Claas Arion 620', 'Claas 35', 'Claas Axion 870', 'Case Maxxum 110', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 640', 'Claas Arion 420', 'Claas Axion 930', 'Massey Ferguson 435', 'Claas Axion 870', 'Case Farmall 95C', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 410', 'Valtra M130', 'Claas Arion 620', 'AGCO DT180A', 'Claas Axos 310', 'Claas Arion 420', 'Claas Arion 650', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 430', 'Claas Axos 330', 'Claas Arion 620', 'Claas 35', 'Claas Arion 410', 'Claas 35', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 420', 'Claas 35', 'Claas Arion 640', 'Claas 35', 'Claas Arion 440', 'Claas 35', 'Claas Arion 430', 'Claas Arion 640', 'Claas Arion 420', 'Case Magnum 315', 'Claas Arion 420', 'Claas Axos 310', 'Claas 35', 'Claas Arion 420', 'Claas Arion 440', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 410', 'Claas 35', 'Claas Arion 620', 'Claas Arion 430', 'Claas Arion 420', 'Claas 35', 'Claas Arion 620', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 430', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas Arion 420', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 410', 'Claas Axion 950', 'Claas Axos 340', 'Claas Arion 420', 'Claas Axos 310', 'Claas Arion 410', 'Claas Arion 620', 'Claas Arion 620', 'Claas 35', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 410', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 650', 'New Holland T6010', 'Case Puma 140 X', 'Claas Nexos 230', 'Claas Nexos 230', 'Case Puma 115', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'New Holland T5.85', 'Claas 35', 'Claas Arion 630', 'Claas Arion 650', 'Claas Axion 850', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 620', 'Claas Axion 830', 'Claas 35', 'JCB 3330', 'JCB Fastrac 4220', 'Claas Arion 650', 'Claas Axion 830', 'Claas Arion 420', 'Claas Arion 420', 'Claas 35', 'Claas Arion 610', 'Claas Xerion 3800', 'Claas Arion 650', 'Claas Arion 420', 'Claas Arion 650', 'Claas Arion 410', 'Claas Arion 440', 'Claas 35', 'Claas Arion 420', 'Claas Axion 830', 'Claas Arion 650', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 650', 'Claas Arion 420', 'Case 600', 'Claas Arion 460', 'JCB Fastrac 4220', 'Claas Arion 620', 'Claas Arion 620', 'Claas Arion 660', 'Renault Master 1', 'Claas Arion 610', 'Claas Axion 830', 'Claas Arion 650', 'Claas 35', 'JCB Fastrac 4220', 'Claas Arion 610', 'Claas 35', 'Claas Arion 420', 'Claas Nexos 220', 'Claas Axion 830', 'Claas Arion 650', 'Claas Arion 630', 'Claas 3300 Trac', 'Claas Arion 420', 'Claas Arion 420', 'Claas 35', 'Claas Arion 630', 'Claas Arion 420', 'Claas Arion 610', 'Claas Arion 410', 'Claas Axos 330', 'Claas Arion 640', 'Claas Arion 420', 'Case Puma 125', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 610', 'Claas Arion 640', 'JCB 3330', 'Claas Arion 610', 'Massey Ferguson 7619', 'Claas Nexos 230', 'John Deere 6230', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 650', 'Claas Nexos 230', 'Claas Arion 420', 'Claas Arion 660', 'New Holland T7030', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 610', 'Claas Arion 640', 'Claas Axion 830', 'Claas 35', 'Claas Arion 650', 'Claas Arion 420', 'Zetor 2011', 'Massey Ferguson 3080', 'JCB 3330', 'Case CVX 150', 'Claas Arion 420', 'Claas Axion 920', 'Claas Axion 870', 'JCB Fastrac 4220', 'Claas Arion 420', 'Claas Arion 650', 'Claas Axion 850', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'McCormick F120', 'Claas Axos 310', 'Case Puma 165 X', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 630', 'Claas Arion 420', 'Claas Arion 650', 'Claas Arion 630', 'Claas Arion 430', 'Claas Arion 440', 'Claas 35', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 620', 'Claas Ares 697', 'John Deere 6520', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axion 810', 'JCB Fastrac 4220', 'Claas Arion 630', 'Claas Axion 820', 'Claas Arion 420', 'Claas Arion 530', 'Tafe 3600', 'Claas Arion 650', 'Landini 50', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 640', 'Claas Arion 420', 'JCB Fastrac 4220', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 530', 'Case Puma 115', 'Claas Arion 430', 'Claas Arion 420', 'JCB 3330', 'Claas Arion 420', 'Claas 35', 'Claas 35', 'Claas Arion 430', 'Claas Arion 420', 'New Holland TS100', 'Claas Arion 420', 'Claas 35', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 420', 'New Holland T7.250', 'Claas Arion 430', 'Claas Arion 650', 'Claas Arion 640', 'Claas Arion 640', 'Claas Arion 620', 'JCB Fastrac 4220', 'Claas Arion 420', 'Claas 35', 'Claas Arion 650', 'Claas 35', 'Claas Arion 420', 'Claas Arion 610', 'Claas Arion 430', 'Case MXU100', 'Claas Axion 810', 'Claas Arion 640', 'Claas 35', 'Claas Axion 850', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 630', 'Claas 35', 'Claas Arion 510', 'Claas Arion 640', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 640', 'Claas Arion 420', 'Claas Arion 610', 'Fendt 927', 'JCB Fastrac 4220', 'JCB Fastrac 4220', 'Claas Arion 530', 'Claas Arion 420', 'Claas Axion 850', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 640', 'Claas Axion 830', 'Claas Arion 420', 'Claas Arion 640', 'McCormick MTX120', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 440', 'Claas Nexos 230', 'Massey Ferguson 5460', 'Claas Arion 420', 'John Deere 6420', 'Claas 35', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 630', 'Claas Arion 630', 'Claas Axos 330', 'Claas Arion 420', 'Claas Arion 660', 'Massey Ferguson 5440', 'Claas Arion 620', 'Case Optum 270', 'Claas Arion 420', 'Claas 35', 'New Holland TL80', 'Claas 35', 'Claas Arion 640', 'Massey Ferguson 5445', 'Claas 3300 Trac', 'JCB Fastrac 3230', 'New Holland TS90', 'Case Maxxum 115', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axos 310', 'Claas Arion 420', 'Case 600', 'Claas Arion 420', 'Claas 35', 'Claas 35', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 650', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas 35', 'Claas Arion 420', 'Deutz Fahr K420', 'Claas Arion 420', 'John Deere 6420', 'Claas Nexos 230', 'Claas Nexos 230', 'Claas Nexos 230', 'JCB Fastrac 4220', 'Claas Arion 420', 'Claas Nexos 230', 'Claas 35', 'Claas Axos 310', 'New Holland T6020', 'Claas Ares 577', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 620', 'Massey Ferguson 550', 'Claas Arion 430', 'Claas Arion 420', 'Claas Arion 630', 'Claas Arion 630', 'Claas Arion 630', 'Claas Axion 820', 'Claas Arion 640', 'New Holland T6030 Plus', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 430', 'Claas Arion 430', 'Claas Arion 610', 'Claas Arion 430', 'Claas 35', 'Claas Arion 420', 'Massey Ferguson 6270', 'Claas Nexos 230', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 420', 'Kubota M8540', 'Claas Arion 420', 'Claas Axos 340', 'Claas Arion 420', 'Claas Arion 620', 'Claas Arion 430', 'JCB Fastrac 4220', 'Claas Arion 420', 'Claas 35', 'Claas Arion 660', 'Case 600', 'New Holland T6030 Plus', 'Claas 35', 'Claas Arion 420', 'Claas Arion 420', 'Claas Arion 510', 'Renault Super 3', 'Kubota A-175', 'Claas Arion 420', 'Claas Arion 420', 'Claas Axos 330', 'Claas Arion 420', 'Claas Arion 42

In [62]:
df['new_combined_cosine'] = new_combined_cosine_list
df['new_cosine_mapped_HP'] = (df['new_combined_cosine']).map(dictionary)

In [63]:
df

,ReportingPeriod,SourceInstanceCd,ConsolidationCd,BusinessUnitDesc,AgreementNbr,AgreementClassificationRefCd,AgreementStatusRefCd,Agreement_Exposure_EUR,Agreement_NetPrincipalBalanceAmt_EUR,FinanceAgreementLineNbr,...,new_ModelDescr,new_CombinedColumn,new_mapped_HP,new_Jaccard_mapped_HP,new_combined_Levenshtein,new_Levenshtein_mapped_HP,new_combined_cosine,new_cosine_mapped_HP,CombinedColumn,new_combined_Jaccard
0,M202110,INFAU,AGAAU,Food & Agriculture,016-0034538-004,BLO,BOOKED,32180.796374,32180.796374,016-0034538-004_488868,...,7250 TTV,Deutz Fahr 7250 TTV,236,236,Deutz Fahr 7250 TTV,236,Deutz Fahr 4.85,82,Deutz Fahr 7250TTV,Deutz Fahr 7250 TTV
1,M202110,INFAU,AGAAU,Food & Agriculture,016-0038548-001,BLO,BOOKED,109052.852056,109052.852056,016-0038548-001_529392,...,N 180a,Claas N 180a,NaN,114,Claas Axion 810,200,Claas Axion 810,200,Claas AXION 810,AGCO Allis 8610
2,M202110,INFAU,AGAAU,Food & Agriculture,016-0044635-001,BLO,BOOKED,28089.070897,28089.070897,016-0044635-001_477195,...,MTX110,McCormick MTX110,116,116,McCormick MTX110,116,McCormick C100,102,McCormick TMAX100PS,McCormick MTX110
3,M202110,INFAU,AGAAU,Food & Agriculture,016-0054437-001,BLO,BOOKED,24748.760117,24748.760117,016-0054437-001_501417,...,6160 TTV,Deutz Fahr 6160 TTV,155,155,Deutz Fahr TTV 610,157,Deutz Fahr 4.85,82,Deutz Fahr TTV610,Deutz Fahr 6160 TTV
4,M202110,INFAU,AGAAU,Food & Agriculture,016-0061278-003,BLO,BOOKED,20454.509550,20371.246358,016-0061278-003_314895,...,1255 XL,Case 1255 XL,125,125,Case MXU115 Value,116,Case Maxxum 125,125,Case MAXXUM 125 & LOADER,Case MXU125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4866,M202110,INFAU,AGANZ,Food & Agriculture,282-0454379-001,BLO,BOOKED,42681.457769,42681.457769,282-0454379-001_482101,...,7R 210,John Deere 7R 210,210,210,John Deere 6130R,130,John Deere 6130R,130,John Deere 6130R (2017),John Deere 7R 210
4867,M202110,INFAU,AGANZ,Food & Agriculture,282-0458168-001,BLO,BOOKED,37816.362965,37816.362965,282-0458168-001_512843,...,6130R,John Deere 6130R,130,130,John Deere 6130R,130,John Deere 6130R,130,John Deere 6130R,John Deere 6130R
4868,M202110,INFAU,AGANZ,Food & Agriculture,282-0498175-001,BLO,BOOKED,150660.428466,150660.428466,282-0498175-001_510073,...,6215 RC,John Deere 6215 RC,NaN,23,John Deere 6215R,215,John Deere 6215R,215,John Deere 6215R (2020),John Deere 1025R
4869,M202110,INFAU,AGANZ,Food & Agriculture,282-0514496-001,BLO,BOOKED,95017.877370,95017.877370,282-0514496-001_530507,...,6215 RC,John Deere 6215 RC,NaN,23,John Deere 6155R,155,John Deere 6155R,155,John Deere 6155R (2019),John Deere 1025R
4870,M202110,INFAU,AGANZ,Food & Agriculture,282-0527441-001,BLO,BOOKED,35372.722236,35372.722236,282-0527441-001_526297,...,1026R,John Deere 1026R,25,25,John Deere 6210R,210,John Deere 6210R,210,John Deere 6210R,John Deere 1026R

In [64]:
# Specify the path and filename for the Excel file
excel_filename = 'advanced_tractor_output_3rd_method.xlsx'

# Export the DataFrame to an Excel file
df.to_excel(excel_filename, index=False)

print(f"DataFrame exported to {excel_filename}")

DataFrame exported to advanced_tractor_output_3rd_method.xlsx